/** 채용 공고(워크넷) 화면 문구 — 50~60대 가독성 기준 */

export const PUBLIC_JOBS_COPY = {
  pageTitle: "청소·용역 채용",
  pageLead: "우리 지역 일자리와 급여가 높은 곳을 한눈에 확인하세요.",
  regionButton: "지역 바꾸기",
  regionDefaultLabel: "서울 전체",
  regionNationalLabel: "전국",
  regionCountSuffix: "건",
  spotlightSectionLabel: "우리 지역 · 전국 한눈에",
  spotlightStripLabel: "급여·마감 요약",
  spotlightStripLocalPay: "지역 최고",
  spotlightStripNationalPay: "전국 최고",
  spotlightStripClosing: "7일 내 마감",
  spotlightStripClosingUnit: "건",
  spotlightStripClosingNone: "없음",
  spotlightLocalPayTitle: "이 지역 급여 1위",
  spotlightLocalClosingTitle: "이 지역 마감 임박",
  spotlightNationalPayTitle: "전국 급여 1위",
  spotlightNationalClosingTitle: "전국 마감 임박",
  spotlightPayTitle: "이 지역 급여 1위",
  spotlightPayEmpty: "표시할 공고가 없습니다.",
  spotlightClosingTitle: "마감이 임박한 공고",
  spotlightClosingEmpty: "마감 임박 공고가 없습니다.",
  spotlightCta: "공고 보기",
  spotlightWorknetCta: "고용24 원문",
  feedTitle: "채용 공고",
  paySortNote: "※ 급여순은 비교용 월 환산 기준입니다. 실제 급여는 고용24 표기(시급·일당·월급)를 확인하세요.",
  feedEmpty: "선택한 지역에 맞는 공고가 없습니다.",
  feedEmptyHint: "지역을 바꿔 보시거나 아래 전국 급여 상위 공고를 참고해 주세요.",
  feedFallbackTitle: "전국 급여 상위",
  syncedPrefix: "고용24 기준",
  sourceNote: "고용24(워크넷)에서 제공한 채용정보입니다.",
  externalCta: "고용24에서 지원·상세 보기",
  externalCtaSub: "고용24 워크넷에서 원문·지원을 진행합니다",
  cardDetailCta: "자세히",
  cardWorknetCta: "바로가기",
  rowDetailCta: "자세히",
  rowWorknetCta: "바로가기",
  shareButton: "카톡으로 공유",
  shareButtonCompact: "공유",
  shareCopied: "링크를 복사했어요",
  shareCopiedCompact: "복사됨",
  sharePending: "공유 준비 중…",
  densityToggleLabel: "목록 보기 방식",
  densityCompact: "한눈에",
  densityComfortable: "글씨 크게",
  tablePay: "급여",
  tableRegion: "지역",
  tableClosing: "마감",
  tablePreset: "직종",
  tableTitle: "공고명",
  tableAction: "자세히",
  detailChecklistTitle: "확인해 보세요",
  detailApplyGuideTitle: "지원 전 더 확인",
  detailRegionMoreJobs: "공고 더 보기",
  detailSameRegion: "같은 지역 다른 공고",
  attribution:
    "본 자료는 고용노동부 고용24(www.work24.go.kr)에서 제공된 정보이며, 무단복제 및 배포를 금지합니다.",
  payNegotiable: "급여 협의",
  platformJobsLink: "플랫폼 구인 보기",
} as const;
