import type {
  ContaminantMasterExt,
  MaterialContaminantMaster,
  SolutionPage,
  SolutionsDb,
} from "@/lib/knowledge-hub/solutions/types";
import {
  SOLUTION_PARTS,
  SOLUTION_PLACES,
  SOLUTION_SPACES,
} from "@/lib/knowledge-hub/solutions/taxonomy";

const CONTAMINANT_MASTERS: ContaminantMasterExt[] = [
  {
    contaminantId: "limescale",
    defaultProductIds: ["kiehl-powerfix-gel", "kiehl-santex", "kiehl-vinoxin"],
    baseGuide:
      "요석은 소변·석회가 굳은 무기질 오염입니다. 산성 계열 세제와 적절한 접촉 시간 후 강한 연마 없이 제거합니다. 재질별 희석·금기를 확인하세요.",
    warnings: [
      "락스·염소계·알칼리성 세제와 혼합하지 않는다.",
      "크롬 수전·대리석·황동·알루미늄 등에는 사용하지 않는다.",
      "보호장갑·보안경을 착용한다.",
    ],
  },
  {
    contaminantId: "lime-deposit",
    defaultProductIds: ["kiehl-vinoxin", "kiehl-tornado"],
    baseGuide: "석회·백화는 경수 잔류·석회질 침착입니다. 요석과 구분하되 산성 세정·린스 흐름은 유사합니다.",
  },
  {
    contaminantId: "water-spot",
    defaultProductIds: ["kiehl-tornado", "kiehl-glasking"],
    baseGuide: "물때는 물기 건조 자국입니다. 유리·수전·도기에서 흔하며, 마른 뒤 전용·중성~약산성으로 닦아냅니다.",
  },
  {
    contaminantId: "soap-scum",
    defaultProductIds: ["kiehl-tornado", "kiehl-tablefit"],
    baseGuide: "비누찌꺼기는 지방·계면활성제 잔류가 뭉친 오염입니다. 알칼리~중성으로 불리게 한 뒤 린스합니다.",
  },
  {
    contaminantId: "mold",
    defaultProductIds: ["kiehl-santex", "kiehl-tornado"],
    baseGuide: "곰팡이는 표백만으로 끝나지 않습니다. 실리콘·줄눈은 표면 처리와 습도 관리가 함께 필요합니다.",
    warnings: ["밀폐·환기 부족 시 재발합니다. 락스 단독 의존을 피하세요."],
  },
  {
    contaminantId: "nicotine",
    defaultProductIds: ["kiehl-tornado", "kiehl-powerfix-gel"],
    baseGuide: "니코틴·담배 잔류는 천장·환풍기·실리콘에 잘 붙습니다. 알칼리·디그리서 계열로 단계 세정합니다.",
  },
  {
    contaminantId: "stain-discoloration",
    defaultProductIds: ["kiehl-tornado", "kiehl-santex"],
    baseGuide: "찌든 때·변색은 원인에 따라 제품이 달라집니다. 부위·재질을 확인한 뒤 처방합니다.",
  },
  {
    contaminantId: "odor",
    defaultProductIds: ["kiehl-tornado"],
    baseGuide: "악취는 표면 오염 제거와 배수·트랩 점검이 우선입니다. 향만 덮지 마세요.",
  },
  {
    contaminantId: "rust",
    defaultProductIds: ["kiehl-ruginoff", "kiehl-vinoxin"],
    baseGuide: "녹은 산성 녹 제거 후 즉시 중화·린스합니다. 도금·약한 금속은 사전 테스트하세요.",
  },
  {
    contaminantId: "grease",
    defaultProductIds: ["kiehl-powerfix-gel", "kiehl-tornado"],
    baseGuide: "기름때는 알칼리·유화 세제와 온수로 녹인 뒤 충분히 린스합니다.",
  },
  {
    contaminantId: "dust",
    defaultProductIds: ["kiehl-tornado"],
    baseGuide: "먼지는 건식→습식 순으로 제거하고, 천장·환풍기는 낙하 오염에 주의합니다.",
  },
];

const MATERIAL_CONTAMINANTS: MaterialContaminantMaster[] = [
  {
    id: "porcelain-limescale",
    materialId: "porcelain",
    contaminantId: "limescale",
    notes: "도기 변기·소변기 요석 — 산성 접촉 후 소프트 도구",
    recipeSlugs: ["powerfix-gel-neat-toilet-limescale", "santex-toilet-neat"],
  },
  {
    id: "porcelain-water-spot",
    materialId: "porcelain",
    contaminantId: "water-spot",
  },
  {
    id: "glass-water-spot",
    materialId: "glass",
    contaminantId: "water-spot",
  },
  {
    id: "glass-lime-deposit",
    materialId: "glass",
    contaminantId: "lime-deposit",
  },
  {
    id: "chrome-faucet-water-spot",
    materialId: "chrome-faucet",
    contaminantId: "water-spot",
    warnings: ["수전 도금은 연마·강산을 피하세요."],
  },
  {
    id: "chrome-faucet-rust",
    materialId: "chrome-faucet",
    contaminantId: "rust",
  },
  {
    id: "silicone-mold",
    materialId: "silicone",
    contaminantId: "mold",
    warnings: ["손상된 실리콘은 교체가 필요할 수 있습니다."],
  },
  {
    id: "grout-mold",
    materialId: "grout",
    contaminantId: "mold",
  },
  {
    id: "ceramic-tile-water-spot",
    materialId: "ceramic-tile",
    contaminantId: "water-spot",
  },
  {
    id: "ceramic-tile-limescale",
    materialId: "ceramic-tile",
    contaminantId: "limescale",
  },
];

type Row = Omit<SolutionPage, "id" | "status" | "slug"> & { slug?: string };

function toPage(r: Row): SolutionPage {
  const slug = r.slug ?? r.contaminantId;
  return {
    ...r,
    slug,
    id: `${r.placeId}__${r.spaceId}__${r.partId}__${slug}`,
    status: "published",
  };
}

/** MVP allowlist: home bathroom/restroom + shop restroom (~50) */
const ROWS: Row[] = [
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "toilet",
    contaminantId: "limescale",
    title: "가정집 화장실 변기 요석 제거",
    materialId: "porcelain",
    materialContaminantId: "porcelain-limescale",
    productIds: ["kiehl-powerfix-gel", "kiehl-santex"],
    placeContext: "가정집 양변기 도기면의 요석이 수면선·가장자리에 붙는 경우가 많습니다.",
    description:
      "가정집 화장실 변기 요석 제거 — 한줄 요약, 추천 세제, 제거 단계, 주의사항.",
    detail: {
      summary:
        "변기에 노랗거나 갈색으로 단단하게 붙어 있는 오염은 대부분 요석입니다.",
      difficulty: 5,
      locations: ["변기 수면 아래", "변기 테두리", "배수구"],
      recommendations: [
        { productId: "kiehl-powerfix-gel", label: "키엘 파워픽스젤", rating: 5 },
        { productId: "kiehl-santex", label: "산성세제", rating: 4 },
        { label: "구연산", rating: 2 },
      ],
      methodSteps: [
        "변기 내부 혹은 배수구의 물을 가능한 한 낮춘다.",
        "파워픽스젤 원액을 오염 부위에 충분히 도포한다.",
        "약 5분 방치한다. (표면에서 세제가 마르지 않게 한다.)",
        "변기솔·내산성 수세미로 문지른 뒤 깨끗한 물로 헹군다.",
        "남으면 짧은 반응과 헹굼을 반복한다.",
      ],
      cautions: ["락스 혼합 금지", "대리석 사용 금지", "장갑 착용"],
      ifFails: ["요석이 아닌 백시멘트", "오랫동안 굳은 석회", "도기 손상"],
    },
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "toilet",
    contaminantId: "water-spot",
    title: "가정집 화장실 변기 물때 제거",
    materialId: "porcelain",
    description: "가정집 화장실 변기 물때 제거 안내.",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "toilet",
    contaminantId: "stain-discoloration",
    slug: "stubborn-stain",
    title: "가정집 화장실 변기 찌든때 제거",
    materialId: "porcelain",
    placeContext: "찌든 때는 요석·물때와 겹칠 수 있어 원인을 나눈 뒤 순서대로 처방합니다.",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "toilet",
    contaminantId: "nicotine",
    title: "가정집 화장실 변기 니코틴 제거",
    materialId: "porcelain",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "toilet",
    contaminantId: "stain-discoloration",
    slug: "discoloration",
    title: "가정집 화장실 변기 변색 제거",
    materialId: "porcelain",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "toilet",
    contaminantId: "odor",
    title: "가정집 화장실 변기 악취 제거",
    materialId: "porcelain",
    placeContext: "변기 악취는 트랩·가장자리 잔류·배수와 함께 확인합니다.",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "sink",
    contaminantId: "water-spot",
    title: "가정집 화장실 세면대 물때 제거",
    materialId: "porcelain",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "sink",
    contaminantId: "soap-scum",
    title: "가정집 화장실 세면대 비누찌꺼기 제거",
    materialId: "porcelain",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "sink",
    contaminantId: "lime-deposit",
    title: "가정집 화장실 세면대 석회 제거",
    materialId: "porcelain",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "faucet",
    contaminantId: "water-spot",
    title: "가정집 화장실 수전 물때 제거",
    materialId: "chrome-faucet",
    materialContaminantId: "chrome-faucet-water-spot",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "faucet",
    contaminantId: "water-spot",
    slug: "sink-faucet-water-spot",
    title: "가정집 화장실 세면대 수전 물때 제거",
    materialId: "chrome-faucet",
    materialContaminantId: "chrome-faucet-water-spot",
    placeContext: "세면대 수전 도금면의 물때·물때가 끼기 쉽습니다.",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "faucet",
    contaminantId: "rust",
    title: "가정집 화장실 세면대 수전 녹 제거",
    materialId: "chrome-faucet",
    materialContaminantId: "chrome-faucet-rust",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "sink",
    contaminantId: "soap-scum",
    slug: "soap-scum-general",
    title: "가정집 화장실 비누찌꺼기 제거",
    placeContext: "세면대·타일·수전 주변 비누막을 함께 볼 때.",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "mirror",
    contaminantId: "water-spot",
    title: "가정집 화장실 거울 물때 제거",
    materialId: "glass",
    materialContaminantId: "glass-water-spot",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "mirror",
    contaminantId: "lime-deposit",
    slug: "whitening",
    title: "가정집 화장실 거울 백화 제거",
    materialId: "glass",
    materialContaminantId: "glass-lime-deposit",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "mirror",
    contaminantId: "lime-deposit",
    title: "가정집 화장실 거울 석회 제거",
    materialId: "glass",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "shower-booth",
    contaminantId: "water-spot",
    title: "가정집 화장실 샤워부스 유리 물때 제거",
    materialId: "glass",
    materialContaminantId: "glass-water-spot",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "shower-booth",
    contaminantId: "lime-deposit",
    title: "가정집 화장실 샤워부스 석회 제거",
    materialId: "glass",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "shower-booth",
    contaminantId: "mold",
    slug: "silicone-mold",
    title: "가정집 화장실 샤워부스 실리콘 곰팡이 제거",
    materialId: "silicone",
    materialContaminantId: "silicone-mold",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "silicone",
    contaminantId: "mold",
    title: "가정집 화장실 실리콘 곰팡이 제거",
    materialId: "silicone",
    materialContaminantId: "silicone-mold",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "silicone",
    contaminantId: "stain-discoloration",
    slug: "discoloration",
    title: "가정집 화장실 실리콘 변색 제거",
    materialId: "silicone",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "silicone",
    contaminantId: "nicotine",
    title: "가정집 화장실 실리콘 니코틴 제거",
    materialId: "silicone",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "grout",
    contaminantId: "mold",
    title: "가정집 화장실 줄눈 곰팡이 제거",
    materialId: "grout",
    materialContaminantId: "grout-mold",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "grout",
    contaminantId: "lime-deposit",
    slug: "whitening",
    title: "가정집 화장실 줄눈 백화 제거",
    materialId: "grout",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "grout",
    contaminantId: "water-spot",
    title: "가정집 화장실 줄눈 물때 제거",
    materialId: "grout",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "grout",
    contaminantId: "stain-discoloration",
    slug: "discoloration",
    title: "가정집 화장실 줄눈 변색 제거",
    materialId: "grout",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "tile",
    contaminantId: "water-spot",
    title: "가정집 화장실 타일 물때 제거",
    materialId: "ceramic-tile",
    materialContaminantId: "ceramic-tile-water-spot",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "tile",
    contaminantId: "limescale",
    title: "가정집 화장실 타일 요석 제거",
    materialId: "ceramic-tile",
    materialContaminantId: "ceramic-tile-limescale",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "tile",
    contaminantId: "lime-deposit",
    slug: "whitening",
    title: "가정집 화장실 타일 백화 제거",
    materialId: "ceramic-tile",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "tile",
    contaminantId: "lime-deposit",
    title: "가정집 화장실 타일 석회 제거",
    materialId: "ceramic-tile",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "tile",
    contaminantId: "soap-scum",
    title: "가정집 화장실 타일 비누찌꺼기 제거",
    materialId: "ceramic-tile",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "tile",
    contaminantId: "mold",
    title: "가정집 화장실 타일 곰팡이 제거",
    materialId: "ceramic-tile",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "ceiling",
    contaminantId: "nicotine",
    title: "가정집 화장실 천장 니코틴 제거",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "ceiling",
    contaminantId: "mold",
    title: "가정집 화장실 천장 곰팡이 제거",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "ceiling",
    contaminantId: "dust",
    title: "가정집 화장실 천장 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "fan",
    contaminantId: "nicotine",
    title: "가정집 화장실 환풍기 니코틴 제거",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "fan",
    contaminantId: "grease",
    title: "가정집 화장실 환풍기 기름때 제거",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "fan",
    contaminantId: "dust",
    title: "가정집 화장실 환풍기 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "restroom",
    partId: "tile",
    contaminantId: "mold",
    slug: "mold-general",
    title: "가정집 화장실 곰팡이 제거",
    placeContext: "타일·줄눈·실리콘을 넓게 볼 때의 입구 페이지입니다. 부위별로 처방을 세분화하세요.",
  },
  // —— 가정집 주방
  {
    placeId: "home",
    spaceId: "kitchen",
    partId: "sink",
    contaminantId: "water-spot",
    title: "가정집 주방 싱크대 물때 제거",
    materialId: "stainless",
  },
  {
    placeId: "home",
    spaceId: "kitchen",
    partId: "sink",
    contaminantId: "lime-deposit",
    title: "가정집 주방 싱크대 석회 제거",
    materialId: "stainless",
  },
  {
    placeId: "home",
    spaceId: "kitchen",
    partId: "sink",
    contaminantId: "grease",
    title: "가정집 주방 싱크대 기름때 제거",
    materialId: "stainless",
  },
  {
    placeId: "home",
    spaceId: "kitchen",
    partId: "sink",
    contaminantId: "rust",
    title: "가정집 주방 싱크대 녹 제거",
    materialId: "stainless",
  },
  {
    placeId: "home",
    spaceId: "kitchen",
    partId: "faucet",
    contaminantId: "water-spot",
    title: "가정집 주방 싱크대 수전 물때 제거",
    materialId: "chrome-faucet",
    materialContaminantId: "chrome-faucet-water-spot",
  },
  {
    placeId: "home",
    spaceId: "kitchen",
    partId: "countertop",
    contaminantId: "stain-discoloration",
    slug: "stubborn-stain",
    title: "가정집 주방 상판 찌든때 제거",
  },
  {
    placeId: "home",
    spaceId: "kitchen",
    partId: "hood",
    contaminantId: "grease",
    title: "가정집 주방 후드 기름때 제거",
  },
  {
    placeId: "home",
    spaceId: "kitchen",
    partId: "tile",
    contaminantId: "grease",
    title: "가정집 주방 타일 기름때 제거",
    materialId: "ceramic-tile",
  },
  {
    placeId: "home",
    spaceId: "kitchen",
    partId: "drain",
    contaminantId: "odor",
    title: "가정집 주방 배수구 악취 제거",
  },
  // —— 거실
  {
    placeId: "home",
    spaceId: "living",
    partId: "floor",
    contaminantId: "dust",
    title: "가정집 거실 바닥 먼지 제거",
    materialId: "laminate-wood",
  },
  {
    placeId: "home",
    spaceId: "living",
    partId: "sofa",
    contaminantId: "stain-discoloration",
    slug: "stubborn-stain",
    title: "가정집 거실 소파 찌든때 제거",
  },
  {
    placeId: "home",
    spaceId: "living",
    partId: "aircon",
    contaminantId: "mold",
    title: "가정집 거실 에어컨 곰팡이 제거",
  },
  {
    placeId: "home",
    spaceId: "living",
    partId: "aircon",
    contaminantId: "dust",
    title: "가정집 거실 에어컨 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "living",
    partId: "wallpaper",
    contaminantId: "mold",
    title: "가정집 거실 벽지 곰팡이 제거",
  },
  {
    placeId: "home",
    spaceId: "living",
    partId: "ceiling",
    contaminantId: "nicotine",
    title: "가정집 거실 천장 니코틴 제거",
  },
  {
    placeId: "home",
    spaceId: "living",
    partId: "blind",
    contaminantId: "dust",
    title: "가정집 거실 블라인드 먼지 제거",
  },
  // —— 침실
  {
    placeId: "home",
    spaceId: "bedroom",
    partId: "mattress",
    contaminantId: "dust",
    title: "가정집 침실 매트리스 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "bedroom",
    partId: "mattress",
    contaminantId: "odor",
    title: "가정집 침실 매트리스 악취 제거",
  },
  {
    placeId: "home",
    spaceId: "bedroom",
    partId: "floor",
    contaminantId: "dust",
    title: "가정집 침실 바닥 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "bedroom",
    partId: "wallpaper",
    contaminantId: "mold",
    title: "가정집 침실 벽지 곰팡이 제거",
  },
  // —— 현관
  {
    placeId: "home",
    spaceId: "entrance",
    partId: "floor",
    contaminantId: "dust",
    title: "가정집 현관 바닥 먼지 제거",
    materialId: "ceramic-tile",
  },
  {
    placeId: "home",
    spaceId: "entrance",
    partId: "shoe-cabinet",
    contaminantId: "dust",
    title: "가정집 현관 신발장 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "entrance",
    partId: "shoe-cabinet",
    contaminantId: "odor",
    title: "가정집 현관 신발장 악취 제거",
  },
  {
    placeId: "home",
    spaceId: "entrance",
    partId: "door-frame",
    contaminantId: "dust",
    title: "가정집 현관 문틀 먼지 제거",
  },
  // —— 베란다
  {
    placeId: "home",
    spaceId: "balcony",
    partId: "floor",
    contaminantId: "dust",
    title: "가정집 베란다 바닥 먼지 제거",
    materialId: "ceramic-tile",
  },
  {
    placeId: "home",
    spaceId: "balcony",
    partId: "drain",
    contaminantId: "odor",
    title: "가정집 베란다 배수구 악취 제거",
  },
  {
    placeId: "home",
    spaceId: "balcony",
    partId: "screen",
    contaminantId: "dust",
    title: "가정집 베란다 방충망 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "balcony",
    partId: "sash-rail",
    contaminantId: "dust",
    title: "가정집 베란다 샷시 먼지 제거",
  },
  // —— 세탁실·다용도실
  {
    placeId: "home",
    spaceId: "laundry",
    partId: "drain",
    contaminantId: "odor",
    title: "가정집 세탁실 배수구 악취 제거",
  },
  {
    placeId: "home",
    spaceId: "laundry",
    partId: "floor",
    contaminantId: "mold",
    title: "가정집 다용도실 바닥 곰팡이 제거",
  },
  {
    placeId: "home",
    spaceId: "utility",
    partId: "faucet",
    contaminantId: "water-spot",
    title: "가정집 다용도실 수전 물때 제거",
    materialId: "chrome-faucet",
  },
  {
    placeId: "home",
    spaceId: "laundry",
    partId: "molding",
    contaminantId: "dust",
    title: "가정집 세탁실 몰딩 먼지 제거",
  },
  // —— 창·샷시
  {
    placeId: "home",
    spaceId: "windows",
    partId: "window",
    contaminantId: "water-spot",
    title: "가정집 유리창 물때 제거",
    materialId: "glass",
  },
  {
    placeId: "home",
    spaceId: "windows",
    partId: "sash-rail",
    contaminantId: "dust",
    title: "가정집 샷시 창틀 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "windows",
    partId: "sash-rail",
    contaminantId: "grease",
    title: "가정집 샷시 찌든때 제거",
    slug: "stubborn-grease",
  },
  {
    placeId: "home",
    spaceId: "windows",
    partId: "screen",
    contaminantId: "dust",
    title: "가정집 방충망 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "windows",
    partId: "sash-rail",
    contaminantId: "mold",
    title: "가정집 창틀 곰팡이 제거",
  },
  // —— 서재
  {
    placeId: "home",
    spaceId: "study",
    partId: "desk",
    contaminantId: "dust",
    title: "가정집 서재 책상 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "study",
    partId: "floor",
    contaminantId: "dust",
    title: "가정집 공부방 바닥 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "study",
    partId: "window",
    contaminantId: "water-spot",
    title: "가정집 서재 유리창 물때 제거",
  },
  // —— 드레스룸
  {
    placeId: "home",
    spaceId: "dressroom",
    partId: "closet",
    contaminantId: "mold",
    title: "가정집 드레스룸 옷장 곰팡이 제거",
  },
  {
    placeId: "home",
    spaceId: "dressroom",
    partId: "closet",
    contaminantId: "odor",
    title: "가정집 드레스룸 옷장 악취 제거",
  },
  {
    placeId: "home",
    spaceId: "dressroom",
    partId: "floor",
    contaminantId: "dust",
    title: "가정집 드레스룸 바닥 먼지 제거",
  },
  // —— 팬트리
  {
    placeId: "home",
    spaceId: "pantry",
    partId: "closet",
    contaminantId: "dust",
    title: "가정집 팬트리 선반 먼지 제거",
  },
  {
    placeId: "home",
    spaceId: "pantry",
    partId: "closet",
    contaminantId: "grease",
    title: "가정집 팬트리 기름때 제거",
  },
  // —— shop restroom
  {
    placeId: "shop",
    spaceId: "restroom",
    partId: "urinal",
    contaminantId: "limescale",
    title: "상가 화장실 소변기 요석 제거",
    materialId: "porcelain",
    materialContaminantId: "porcelain-limescale",
    placeContext: "상가·공용 소변기는 요석·악취가 빠르게 쌓입니다. 주기 세정이 중요합니다.",
  },
  {
    placeId: "shop",
    spaceId: "restroom",
    partId: "urinal",
    contaminantId: "water-spot",
    title: "상가 화장실 소변기 물때 제거",
    materialId: "porcelain",
  },
  {
    placeId: "shop",
    spaceId: "restroom",
    partId: "urinal",
    contaminantId: "odor",
    title: "상가 화장실 소변기 악취 제거",
    materialId: "porcelain",
  },
  {
    placeId: "shop",
    spaceId: "restroom",
    partId: "urinal",
    contaminantId: "lime-deposit",
    slug: "whitening",
    title: "상가 화장실 소변기 백화 제거",
    materialId: "porcelain",
  },
  {
    placeId: "shop",
    spaceId: "restroom",
    partId: "urinal",
    contaminantId: "lime-deposit",
    title: "상가 화장실 소변기 석회 제거",
    materialId: "porcelain",
  },
  {
    placeId: "shop",
    spaceId: "restroom",
    partId: "toilet",
    contaminantId: "limescale",
    title: "상가 화장실 양변기 요석 제거",
    materialId: "porcelain",
    materialContaminantId: "porcelain-limescale",
  },
  {
    placeId: "shop",
    spaceId: "restroom",
    partId: "toilet",
    contaminantId: "water-spot",
    title: "상가 화장실 양변기 물때 제거",
    materialId: "porcelain",
  },
  {
    placeId: "shop",
    spaceId: "restroom",
    partId: "sink",
    contaminantId: "water-spot",
    title: "상가 화장실 세면대 물때 제거",
    materialId: "porcelain",
  },
  {
    placeId: "shop",
    spaceId: "restroom",
    partId: "faucet",
    contaminantId: "water-spot",
    title: "상가 화장실 수전 물때 제거",
    materialId: "chrome-faucet",
    materialContaminantId: "chrome-faucet-water-spot",
  },
  {
    placeId: "shop",
    spaceId: "restroom",
    partId: "mirror",
    contaminantId: "water-spot",
    title: "상가 화장실 거울 물때 제거",
    materialId: "glass",
    materialContaminantId: "glass-water-spot",
  },
];

export function buildSolutionsDb(): SolutionsDb {
  return {
    version: 1,
    updatedAt: "2026-07-14",
    places: SOLUTION_PLACES,
    spaces: SOLUTION_SPACES,
    parts: SOLUTION_PARTS,
    contaminantMasters: CONTAMINANT_MASTERS,
    materialContaminants: MATERIAL_CONTAMINANTS,
    pages: ROWS.map(toPage),
  };
}

export const SOURCE_SOLUTIONS_DB = buildSolutionsDb();
