/** Auto-generated from RTMS LAWD CSV — scripts/generate-demand-regions.mjs */

export type DemandRegistryDistrict = {
  /** RTMS sigungu 표기 (예: 강남구, 안동시, 성남시 분당구) */
  gu: string;
  slug: string;
  lawdCd: string;
};

export type DemandRegistryCity = {
  id: string;
  label: string;
  fullLabel: string;
  districts: DemandRegistryDistrict[];
};

export const DEMAND_REGION_REGISTRY: DemandRegistryCity[] = [
  {
    id: "gangwon",
    label: "강원",
    fullLabel: "강원특별자치도",
    districts: [
      { gu: "강릉시", slug: "gareusi-si", lawdCd: "42150" },
      { gu: "고성군", slug: "goseogun-gun", lawdCd: "42820" },
      { gu: "동해시", slug: "dohaesi-si", lawdCd: "42170" },
      { gu: "명주군", slug: "myeojugun-gun", lawdCd: "42840" },
      { gu: "삼척시", slug: "samcheogsi-si", lawdCd: "42230" },
      { gu: "속초시", slug: "sogchosi-si", lawdCd: "42210" },
      { gu: "양구군", slug: "yagugun-gun", lawdCd: "42800" },
      { gu: "양양군", slug: "yayagun-gun", lawdCd: "42830" },
      { gu: "영월군", slug: "yeoworgun-gun", lawdCd: "42750" },
      { gu: "울진군", slug: "urjingun-gun", lawdCd: "42050" },
      { gu: "원주시", slug: "wonjusi-si", lawdCd: "42130" },
      { gu: "인제군", slug: "injegun-gun", lawdCd: "42810" },
      { gu: "정선군", slug: "jeoseongun-gun", lawdCd: "42770" },
      { gu: "철원군", slug: "cheorwongun-gun", lawdCd: "42780" },
      { gu: "춘천시", slug: "chuncheonsi-si", lawdCd: "42110" },
      { gu: "태백시", slug: "taebaegsi-si", lawdCd: "42190" },
      { gu: "평창군", slug: "pyeochagun-gun", lawdCd: "42760" },
      { gu: "홍천군", slug: "hocheongun-gun", lawdCd: "42720" },
      { gu: "화천군", slug: "hwacheongun-gun", lawdCd: "42790" },
      { gu: "횡성군", slug: "hoeseogun-gun", lawdCd: "42730" }
    ],
  },
  {
    id: "gyeonggi",
    label: "경기",
    fullLabel: "경기도",
    districts: [
      { gu: "가평군", slug: "gapyeogun-gun", lawdCd: "41820" },
      { gu: "강화군", slug: "gahwagun-gun", lawdCd: "41880" },
      { gu: "고양시 덕양구", slug: "goya-deogyagu-gu", lawdCd: "41281" },
      { gu: "고양시 일산동구", slug: "goya-irsandogu-gu", lawdCd: "41285" },
      { gu: "고양시 일산서구", slug: "goya-irsanseogu-gu", lawdCd: "41287" },
      { gu: "과천시", slug: "gwacheonsi-si", lawdCd: "41290" },
      { gu: "광명시", slug: "gwamyeosi-si", lawdCd: "41210" },
      { gu: "광주시", slug: "gwajusi-si", lawdCd: "41610" },
      { gu: "구리시", slug: "gurisi-si", lawdCd: "41310" },
      { gu: "군포시", slug: "gunposi-si", lawdCd: "41410" },
      { gu: "김포시", slug: "gimposi-si", lawdCd: "41570" },
      { gu: "남양주시", slug: "namyajusi-si", lawdCd: "41360" },
      { gu: "동두천시", slug: "doducheonsi-si", lawdCd: "41250" },
      { gu: "미금시", slug: "migeumsi-si", lawdCd: "41350" },
      { gu: "부천시", slug: "bucheonsi-si", lawdCd: "41190" },
      { gu: "성남시 분당구", slug: "seonam-bundagu-gu", lawdCd: "41135" },
      { gu: "성남시 수정구", slug: "seonam-sujeogu-gu", lawdCd: "41131" },
      { gu: "성남시 중원구", slug: "seonam-juwongu-gu", lawdCd: "41133" },
      { gu: "송탄시", slug: "sotansi-si", lawdCd: "41230" },
      { gu: "수원시 권선구", slug: "suwon-gwonseongu-gu", lawdCd: "41113" },
      { gu: "수원시 영통구", slug: "suwon-yeotogu-gu", lawdCd: "41117" },
      { gu: "수원시 장안구", slug: "suwon-jaangu-gu", lawdCd: "41111" },
      { gu: "수원시 팔달구", slug: "suwon-pardargu-gu", lawdCd: "41115" },
      { gu: "시흥시", slug: "siheusi-si", lawdCd: "41390" },
      { gu: "안산시 단원구", slug: "ansan-danwongu-gu", lawdCd: "41271" },
      { gu: "안산시 상록구", slug: "ansan-saroggu-gu", lawdCd: "41273" },
      { gu: "안성시", slug: "anseosi-si", lawdCd: "41550" },
      { gu: "안양시 동안구", slug: "anya-doangu-gu", lawdCd: "41173" },
      { gu: "안양시 만안구", slug: "anya-manangu-gu", lawdCd: "41171" },
      { gu: "양주시", slug: "yajusi-si", lawdCd: "41630" },
      { gu: "양평군", slug: "yapyeogun-gun", lawdCd: "41830" },
      { gu: "여주시", slug: "yeojusi-si", lawdCd: "41670" },
      { gu: "연천군", slug: "yeoncheongun-gun", lawdCd: "41800" },
      { gu: "오산시", slug: "osansi-si", lawdCd: "41370" },
      { gu: "옹진군", slug: "ojingun-gun", lawdCd: "41890" },
      { gu: "용인시 기흥구", slug: "yoin-giheugu-gu", lawdCd: "41463" },
      { gu: "용인시 수지구", slug: "yoin-sujigu-gu", lawdCd: "41465" },
      { gu: "용인시 처인구", slug: "yoin-cheoingu-gu", lawdCd: "41461" },
      { gu: "의왕시", slug: "uiwasi-si", lawdCd: "41430" },
      { gu: "의정부시", slug: "uijeobusi-si", lawdCd: "41150" },
      { gu: "이천시", slug: "icheonsi-si", lawdCd: "41500" },
      { gu: "파주시", slug: "pajusi-si", lawdCd: "41480" },
      { gu: "평택시", slug: "pyeotaegsi-si", lawdCd: "41220" },
      { gu: "포천시", slug: "pocheonsi-si", lawdCd: "41650" },
      { gu: "하남시", slug: "hanamsi-si", lawdCd: "41450" },
      { gu: "화성시", slug: "hwaseosi-si", lawdCd: "41590" }
    ],
  },
  {
    id: "gyeongnam",
    label: "경남",
    fullLabel: "경상남도",
    districts: [
      { gu: "거제시", slug: "geojesi-si", lawdCd: "48310" },
      { gu: "거창군", slug: "geochagun-gun", lawdCd: "48880" },
      { gu: "고성군", slug: "goseogun-gun", lawdCd: "48820" },
      { gu: "김해시", slug: "gimhaesi-si", lawdCd: "48250" },
      { gu: "남해군", slug: "namhaegun-gun", lawdCd: "48840" },
      { gu: "밀양시", slug: "miryasi-si", lawdCd: "48270" },
      { gu: "사천시", slug: "sacheonsi-si", lawdCd: "48240" },
      { gu: "산청군", slug: "sancheogun-gun", lawdCd: "48860" },
      { gu: "삼천포시", slug: "samcheonposi-si", lawdCd: "48230" },
      { gu: "양산시", slug: "yasansi-si", lawdCd: "48330" },
      { gu: "울주군", slug: "urjugun-gun", lawdCd: "48770" },
      { gu: "의령군", slug: "uiryeogun-gun", lawdCd: "48720" },
      { gu: "의창군", slug: "uichagun-gun", lawdCd: "48790" },
      { gu: "장승포시", slug: "jaseuposi-si", lawdCd: "48290" },
      { gu: "진주시", slug: "jinjusi-si", lawdCd: "48170" },
      { gu: "창녕군", slug: "chanyeogun-gun", lawdCd: "48740" },
      { gu: "창원시 마산합포구", slug: "chawon-masanhabpogu-gu", lawdCd: "48125" },
      { gu: "창원시 마산회원구", slug: "chawon-masanhoewongu-gu", lawdCd: "48127" },
      { gu: "창원시 성산구", slug: "chawon-seosangu-gu", lawdCd: "48123" },
      { gu: "창원시 의창구", slug: "chawon-uichagu-gu", lawdCd: "48121" },
      { gu: "창원시 진해구", slug: "chawon-jinhaegu-gu", lawdCd: "48129" },
      { gu: "충무시", slug: "chumusi-si", lawdCd: "48210" },
      { gu: "통영시", slug: "toyeosi-si", lawdCd: "48220" },
      { gu: "하동군", slug: "hadogun-gun", lawdCd: "48850" },
      { gu: "함안군", slug: "hamangun-gun", lawdCd: "48730" },
      { gu: "함양군", slug: "hamyagun-gun", lawdCd: "48870" },
      { gu: "합천군", slug: "habcheongun-gun", lawdCd: "48890" }
    ],
  },
  {
    id: "gyeongbuk",
    label: "경북",
    fullLabel: "경상북도",
    districts: [
      { gu: "경산시", slug: "gyeosansi-si", lawdCd: "47290" },
      { gu: "경주시", slug: "gyeojusi-si", lawdCd: "47130" },
      { gu: "고령군", slug: "goryeogun-gun", lawdCd: "47830" },
      { gu: "구미시", slug: "gumisi-si", lawdCd: "47190" },
      { gu: "군위군", slug: "gunwigun-gun", lawdCd: "47720" },
      { gu: "금릉군", slug: "geumreugun-gun", lawdCd: "47860" },
      { gu: "김천시", slug: "gimcheonsi-si", lawdCd: "47150" },
      { gu: "달성군", slug: "darseogun-gun", lawdCd: "47710" },
      { gu: "문경시", slug: "mungyeosi-si", lawdCd: "47280" },
      { gu: "봉화군", slug: "bohwagun-gun", lawdCd: "47920" },
      { gu: "상주시", slug: "sajusi-si", lawdCd: "47250" },
      { gu: "선산군", slug: "seonsangun-gun", lawdCd: "47870" },
      { gu: "성주군", slug: "seojugun-gun", lawdCd: "47840" },
      { gu: "안동시", slug: "andosi-si", lawdCd: "47170" },
      { gu: "영덕군", slug: "yeodeoggun-gun", lawdCd: "47770" },
      { gu: "영양군", slug: "yeoyagun-gun", lawdCd: "47760" },
      { gu: "영일군", slug: "yeoirgun-gun", lawdCd: "47780" },
      { gu: "영주시", slug: "yeojusi-si", lawdCd: "47210" },
      { gu: "영천시", slug: "yeocheonsi-si", lawdCd: "47230" },
      { gu: "영풍군", slug: "yeopugun-gun", lawdCd: "47910" },
      { gu: "예천군", slug: "yecheongun-gun", lawdCd: "47900" },
      { gu: "울릉군", slug: "urreugun-gun", lawdCd: "47940" },
      { gu: "울진군", slug: "urjingun-gun", lawdCd: "47930" },
      { gu: "의성군", slug: "uiseogun-gun", lawdCd: "47730" },
      { gu: "점촌시", slug: "jeomchonsi-si", lawdCd: "47270" },
      { gu: "청도군", slug: "cheodogun-gun", lawdCd: "47820" },
      { gu: "청송군", slug: "cheosogun-gun", lawdCd: "47750" },
      { gu: "칠곡군", slug: "chirgoggun-gun", lawdCd: "47850" },
      { gu: "포항시 남구", slug: "poha-namgu-gu", lawdCd: "47113" },
      { gu: "포항시 북구", slug: "poha-buggu-gu", lawdCd: "47111" }
    ],
  },
  {
    id: "gwangju",
    label: "광주",
    fullLabel: "광주광역시",
    districts: [
      { gu: "광산구", slug: "gwasangu-gu", lawdCd: "29200" },
      { gu: "남구", slug: "namgu-gu", lawdCd: "29155" },
      { gu: "동구", slug: "dogu-gu", lawdCd: "29110" },
      { gu: "북구", slug: "buggu-gu", lawdCd: "29170" },
      { gu: "서구", slug: "seogu-gu", lawdCd: "29140" }
    ],
  },
  {
    id: "daegu",
    label: "대구",
    fullLabel: "대구광역시",
    districts: [
      { gu: "남구", slug: "namgu-gu", lawdCd: "27200" },
      { gu: "달서구", slug: "darseogu-gu", lawdCd: "27290" },
      { gu: "달성군", slug: "darseogun-gun", lawdCd: "27710" },
      { gu: "동구", slug: "dogu-gu", lawdCd: "27140" },
      { gu: "북구", slug: "buggu-gu", lawdCd: "27230" },
      { gu: "서구", slug: "seogu-gu", lawdCd: "27170" },
      { gu: "수성구", slug: "suseogu-gu", lawdCd: "27260" },
      { gu: "중구", slug: "jung-gu", lawdCd: "27110" }
    ],
  },
  {
    id: "daejeon",
    label: "대전",
    fullLabel: "대전광역시",
    districts: [
      { gu: "대덕구", slug: "daedeoggu-gu", lawdCd: "30230" },
      { gu: "동구", slug: "dogu-gu", lawdCd: "30110" },
      { gu: "서구", slug: "seogu-gu", lawdCd: "30170" },
      { gu: "유성구", slug: "yuseogu-gu", lawdCd: "30200" },
      { gu: "중구", slug: "jung-gu", lawdCd: "30140" }
    ],
  },
  {
    id: "busan",
    label: "부산",
    fullLabel: "부산광역시",
    districts: [
      { gu: "강서구", slug: "gangseo-gu", lawdCd: "26440" },
      { gu: "금정구", slug: "geumjeogu-gu", lawdCd: "26410" },
      { gu: "기장군", slug: "gijagun-gun", lawdCd: "26710" },
      { gu: "남구", slug: "namgu-gu", lawdCd: "26290" },
      { gu: "동구", slug: "dogu-gu", lawdCd: "26170" },
      { gu: "동래구", slug: "doraegu-gu", lawdCd: "26260" },
      { gu: "부산진구", slug: "busanjingu-gu", lawdCd: "26230" },
      { gu: "북구", slug: "buggu-gu", lawdCd: "26320" },
      { gu: "사상구", slug: "sasagu-gu", lawdCd: "26530" },
      { gu: "사하구", slug: "sahagu-gu", lawdCd: "26380" },
      { gu: "서구", slug: "seogu-gu", lawdCd: "26140" },
      { gu: "수영구", slug: "suyeogu-gu", lawdCd: "26500" },
      { gu: "연제구", slug: "yeonjegu-gu", lawdCd: "26470" },
      { gu: "영도구", slug: "yeodogu-gu", lawdCd: "26200" },
      { gu: "중구", slug: "jung-gu", lawdCd: "26110" },
      { gu: "해운대구", slug: "haeundaegu-gu", lawdCd: "26350" }
    ],
  },
  {
    id: "seoul",
    label: "서울",
    fullLabel: "서울특별시",
    districts: [
      { gu: "강남구", slug: "gangnam-gu", lawdCd: "11680" },
      { gu: "강동구", slug: "gangdong-gu", lawdCd: "11740" },
      { gu: "강북구", slug: "gangbuk-gu", lawdCd: "11305" },
      { gu: "강서구", slug: "gangseo-gu", lawdCd: "11500" },
      { gu: "관악구", slug: "gwanak-gu", lawdCd: "11620" },
      { gu: "광진구", slug: "gwangjin-gu", lawdCd: "11215" },
      { gu: "구로구", slug: "guro-gu", lawdCd: "11530" },
      { gu: "금천구", slug: "geumcheon-gu", lawdCd: "11545" },
      { gu: "노원구", slug: "nowon-gu", lawdCd: "11350" },
      { gu: "도봉구", slug: "dobong-gu", lawdCd: "11320" },
      { gu: "동대문구", slug: "dongdaemun-gu", lawdCd: "11230" },
      { gu: "동작구", slug: "dongjak-gu", lawdCd: "11590" },
      { gu: "마포구", slug: "mapo-gu", lawdCd: "11440" },
      { gu: "서대문구", slug: "seodaemun-gu", lawdCd: "11410" },
      { gu: "서초구", slug: "seocho-gu", lawdCd: "11650" },
      { gu: "성동구", slug: "seongdong-gu", lawdCd: "11200" },
      { gu: "성북구", slug: "seongbuk-gu", lawdCd: "11290" },
      { gu: "송파구", slug: "songpa-gu", lawdCd: "11710" },
      { gu: "양천구", slug: "yangcheon-gu", lawdCd: "11470" },
      { gu: "영등포구", slug: "yeongdeungpo-gu", lawdCd: "11560" },
      { gu: "용산구", slug: "yongsan-gu", lawdCd: "11170" },
      { gu: "은평구", slug: "eunpyeong-gu", lawdCd: "11380" },
      { gu: "종로구", slug: "jongno-gu", lawdCd: "11110" },
      { gu: "중구", slug: "jung-gu", lawdCd: "11140" },
      { gu: "중랑구", slug: "jungnang-gu", lawdCd: "11260" }
    ],
  },
  {
    id: "sejong",
    label: "세종",
    fullLabel: "세종특별자치시",
    districts: [
      { gu: "세종시", slug: "sejosi-si", lawdCd: "36110" }
    ],
  },
  {
    id: "ulsan",
    label: "울산",
    fullLabel: "울산광역시",
    districts: [
      { gu: "남구", slug: "namgu-gu", lawdCd: "31140" },
      { gu: "동구", slug: "dogu-gu", lawdCd: "31170" },
      { gu: "북구", slug: "buggu-gu", lawdCd: "31200" },
      { gu: "울주군", slug: "urjugun-gun", lawdCd: "31710" },
      { gu: "중구", slug: "jung-gu", lawdCd: "31110" }
    ],
  },
  {
    id: "incheon",
    label: "인천",
    fullLabel: "인천광역시",
    districts: [
      { gu: "강화군", slug: "gahwagun-gun", lawdCd: "28710" },
      { gu: "계양구", slug: "gyeyagu-gu", lawdCd: "28245" },
      { gu: "남동구", slug: "namdogu-gu", lawdCd: "28200" },
      { gu: "동구", slug: "dogu-gu", lawdCd: "28140" },
      { gu: "미추홀구", slug: "michuhorgu-gu", lawdCd: "28177" },
      { gu: "부평구", slug: "bupyeogu-gu", lawdCd: "28237" },
      { gu: "서구", slug: "seogu-gu", lawdCd: "28260" },
      { gu: "연수구", slug: "yeonsugu-gu", lawdCd: "28185" },
      { gu: "옹진군", slug: "ojingun-gun", lawdCd: "28720" },
      { gu: "중구", slug: "jung-gu", lawdCd: "28110" }
    ],
  },
  {
    id: "jeonnam",
    label: "전남",
    fullLabel: "전라남도",
    districts: [
      { gu: "강진군", slug: "gajingun-gun", lawdCd: "46810" },
      { gu: "고흥군", slug: "goheugun-gun", lawdCd: "46770" },
      { gu: "곡성군", slug: "gogseogun-gun", lawdCd: "46720" },
      { gu: "광양시", slug: "gwayasi-si", lawdCd: "46230" },
      { gu: "구례군", slug: "guryegun-gun", lawdCd: "46730" },
      { gu: "나주시", slug: "najusi-si", lawdCd: "46170" },
      { gu: "담양군", slug: "damyagun-gun", lawdCd: "46710" },
      { gu: "동광양시", slug: "dogwayasi-si", lawdCd: "46210" },
      { gu: "목포시", slug: "mogposi-si", lawdCd: "46110" },
      { gu: "무안군", slug: "muangun-gun", lawdCd: "46840" },
      { gu: "보성군", slug: "boseogun-gun", lawdCd: "46780" },
      { gu: "순천시", slug: "suncheonsi-si", lawdCd: "46150" },
      { gu: "승주군", slug: "seujugun-gun", lawdCd: "46760" },
      { gu: "신안군", slug: "sinangun-gun", lawdCd: "46910" },
      { gu: "여수시", slug: "yeosusi-si", lawdCd: "46130" },
      { gu: "영광군", slug: "yeogwagun-gun", lawdCd: "46870" },
      { gu: "영암군", slug: "yeoamgun-gun", lawdCd: "46830" },
      { gu: "완도군", slug: "wandogun-gun", lawdCd: "46890" },
      { gu: "장성군", slug: "jaseogun-gun", lawdCd: "46880" },
      { gu: "장흥군", slug: "jaheugun-gun", lawdCd: "46800" },
      { gu: "진도군", slug: "jindogun-gun", lawdCd: "46900" },
      { gu: "함평군", slug: "hampyeogun-gun", lawdCd: "46860" },
      { gu: "해남군", slug: "haenamgun-gun", lawdCd: "46820" },
      { gu: "화순군", slug: "hwasungun-gun", lawdCd: "46790" }
    ],
  },
  {
    id: "jeonbuk",
    label: "전북",
    fullLabel: "전북특별자치도",
    districts: [
      { gu: "고창군", slug: "gochagun-gun", lawdCd: "45790" },
      { gu: "군산시", slug: "gunsansi-si", lawdCd: "45130" },
      { gu: "금산군", slug: "geumsangun-gun", lawdCd: "45050" },
      { gu: "김제시", slug: "gimjesi-si", lawdCd: "45210" },
      { gu: "남원시", slug: "namwonsi-si", lawdCd: "45190" },
      { gu: "무주군", slug: "mujugun-gun", lawdCd: "45730" },
      { gu: "부안군", slug: "buangun-gun", lawdCd: "45800" },
      { gu: "순창군", slug: "sunchagun-gun", lawdCd: "45770" },
      { gu: "옥구군", slug: "oggugun-gun", lawdCd: "45820" },
      { gu: "완주군", slug: "wanjugun-gun", lawdCd: "45710" },
      { gu: "이리시", slug: "irisi-si", lawdCd: "45150" },
      { gu: "익산시", slug: "igsansi-si", lawdCd: "45140" },
      { gu: "임실군", slug: "imsirgun-gun", lawdCd: "45750" },
      { gu: "장수군", slug: "jasugun-gun", lawdCd: "45740" },
      { gu: "전주시 덕진구", slug: "jeonju-deogjingu-gu", lawdCd: "45113" },
      { gu: "전주시 완산구", slug: "jeonju-wansangu-gu", lawdCd: "45111" },
      { gu: "정읍시", slug: "jeoeubsi-si", lawdCd: "45180" },
      { gu: "정주시", slug: "jeojusi-si", lawdCd: "45170" },
      { gu: "진안군", slug: "jinangun-gun", lawdCd: "45720" }
    ],
  },
  {
    id: "jeju",
    label: "제주",
    fullLabel: "제주특별자치도",
    districts: [
      { gu: "서귀포시", slug: "seogwiposi-si", lawdCd: "50130" },
      { gu: "제주시", slug: "jejusi-si", lawdCd: "50110" }
    ],
  },
  {
    id: "chungnam",
    label: "충남",
    fullLabel: "충청남도",
    districts: [
      { gu: "계룡시", slug: "gyeryosi-si", lawdCd: "44250" },
      { gu: "공주시", slug: "gojusi-si", lawdCd: "44150" },
      { gu: "금산군", slug: "geumsangun-gun", lawdCd: "44710" },
      { gu: "논산시", slug: "nonsansi-si", lawdCd: "44230" },
      { gu: "당진시", slug: "dajinsi-si", lawdCd: "44270" },
      { gu: "대덕군", slug: "daedeoggun-gun", lawdCd: "44720" },
      { gu: "대천시", slug: "daecheonsi-si", lawdCd: "44170" },
      { gu: "보령시", slug: "boryeosi-si", lawdCd: "44180" },
      { gu: "부여군", slug: "buyeogun-gun", lawdCd: "44760" },
      { gu: "서산시", slug: "seosansi-si", lawdCd: "44210" },
      { gu: "서천군", slug: "seocheongun-gun", lawdCd: "44770" },
      { gu: "아산시", slug: "asansi-si", lawdCd: "44200" },
      { gu: "연기군", slug: "yeongigun-gun", lawdCd: "44730" },
      { gu: "예산군", slug: "yesangun-gun", lawdCd: "44810" },
      { gu: "온양시", slug: "onyasi-si", lawdCd: "44190" },
      { gu: "천안시 동남구", slug: "cheonan-donamgu-gu", lawdCd: "44131" },
      { gu: "천안시 서북구", slug: "cheonan-seobuggu-gu", lawdCd: "44133" },
      { gu: "천원군", slug: "cheonwongun-gun", lawdCd: "44850" },
      { gu: "청양군", slug: "cheoyagun-gun", lawdCd: "44790" },
      { gu: "태안군", slug: "taeangun-gun", lawdCd: "44825" },
      { gu: "홍성군", slug: "hoseogun-gun", lawdCd: "44800" }
    ],
  },
  {
    id: "chungbuk",
    label: "충북",
    fullLabel: "충청북도",
    districts: [
      { gu: "괴산군", slug: "goesangun-gun", lawdCd: "43760" },
      { gu: "단양군", slug: "danyagun-gun", lawdCd: "43800" },
      { gu: "보은군", slug: "boeungun-gun", lawdCd: "43720" },
      { gu: "옥천군", slug: "ogcheongun-gun", lawdCd: "43730" },
      { gu: "음성군", slug: "eumseogun-gun", lawdCd: "43770" },
      { gu: "제원군", slug: "jewongun-gun", lawdCd: "43790" },
      { gu: "제천시", slug: "jecheonsi-si", lawdCd: "43150" },
      { gu: "중원군", slug: "juwongun-gun", lawdCd: "43780" },
      { gu: "증평군", slug: "jeupyeogun-gun", lawdCd: "43745" },
      { gu: "진천군", slug: "jincheongun-gun", lawdCd: "43750" },
      { gu: "청원군", slug: "cheowongun-gun", lawdCd: "43710" },
      { gu: "청주시 상당구", slug: "cheoju-sadagu-gu", lawdCd: "43111" },
      { gu: "청주시 서원구", slug: "cheoju-seowongu-gu", lawdCd: "43112" },
      { gu: "청주시 청원구", slug: "cheoju-cheowongu-gu", lawdCd: "43114" },
      { gu: "청주시 흥덕구", slug: "cheoju-heudeoggu-gu", lawdCd: "43113" },
      { gu: "충주시", slug: "chujusi-si", lawdCd: "43130" }
    ],
  }
];
