import type { CleaningKnowledgeDb } from "@/lib/knowledge-hub/cleaning-knowledge/types";

const SRC = {
  weekly: { title: "위클리너스 — 키엘 산텍스 사용법", date: "2026-06-27" },
  mimi: { title: "키엘 카페 — 미미1965 제품 사용법 문의", author: "미미1965", date: "2025-09-03" },
  charlie1: { title: "세정제 길라잡이 [1.재질]", author: "찰리브라운", date: "2025-02-07" },
  charlie2: { title: "세정제 길라잡이 [2.PH와 오염원]", author: "찰리브라운", date: "2025-02-08" },
  charlie4: { title: "세정제 길라잡이 [4.알칼리성 세정제]", author: "찰리브라운", date: "2025-02-11" },
  parketto: { title: "키엘 목재 바닥 세정·왁스 제품 선택", author: "찰리브라운", date: "2021-11-29" },
  shower: { title: "샤워부스 청소 — 페트로날에코 후기", author: "one0668", date: "2023-02-11" },
  kitchen: { title: "주방 기름때 그라셋·엑손포르테 작업", author: "점보크린 시흥점", date: "2026-07-05" },
  jet: { title: "싱크대 묵은 때 제트액티브 후기", author: "금뽕돌 제주", date: "2024-06-04" },
  floor: { title: "에폭시 바닥 베리프롭 문의", author: "The깨끗한클린", date: "2023-07-10" },
  rust: { title: "엘베 녹 비녹신 문의", author: "돌프", date: "2023-08-17" },
  glassLimescale: { title: "유리 물때·석회 제거", author: "찰리브라운", date: "2022-05-17" },
  dryWipe: { title: "마른걸레질 해야 하나", author: "찰리브라운", date: "2024-01-13" },
  glass3: { title: "키엘 유리세정제 3종 비교", author: "찰리브라운", date: "2022-02-09" },
  glassWorkflow: { title: "유리창 청소 GLASS-0001", note: "클린아이덱스 구조화" },
  pinocet: { title: "피노셋 사용법 문의", author: "수비니아빠", date: "2026-07-02" },
  cementTile: { title: "타일 백시멘트 칼리넥스", author: "찰리브라운", date: "2026-07-03" },
  ticleanAlt: { title: "티크린 대체 — 산텍스", author: "찰리브라운", note: "DB-0007" },
};

/** v2 시드 — 커뮤니티·블로그 붙여넣기에서 추출. Cursor ingest 시 mergeKnowledgeDb로 병합 */
export const INITIAL_CLEANING_KNOWLEDGE: CleaningKnowledgeDb = {
  version: 2,
  updatedAt: "2026-07-09T10:45:00.000Z",
  materials: [
    { id: "porcelain", name: "도기·자기(변기·세면대)", riskLevel: "low", notes: "유약 표면. 강산 원액 국소 사용 가능" },
    { id: "ceramic-tile", name: "타일(자기·포세린)", riskLevel: "low" },
    { id: "grout", name: "줄눈·석회질", riskLevel: "medium", notes: "산성 장시간 방치 시 부식 우려" },
    { id: "stainless", name: "스테인레스", riskLevel: "medium", notes: "결 방향 따라 작업. 코팅·등급에 따라 반응 상이" },
    { id: "chrome-faucet", name: "크롬·수전", riskLevel: "medium", notes: "산성 장시간 방치 금지" },
    { id: "marble", name: "대리석·라임스톤", riskLevel: "very_high", notes: "산성·강알칼리 모두 금지" },
    { id: "granite", name: "화강석", riskLevel: "medium", notes: "멘틀 강도 높아 일부 산·알칼리 견딤" },
    { id: "epoxy-floor", name: "에폭시 코팅 바닥", riskLevel: "medium", notes: "수지 왁스 코팅 시 세제·물 사용 제한" },
    { id: "laminate-wood", name: "강마루·강화마루(라미네이팅)", riskLevel: "medium", notes: "목재 전용 제품 사용" },
    { id: "silicone", name: "실리콘(줄·창틀)", riskLevel: "high", notes: "곰팡이 깊이 침투 시 교체가 현실적" },
    { id: "glass", name: "유리", riskLevel: "low" },
    { id: "pvc-deco", name: "데코타일(PVC)", riskLevel: "low", aliases: ["데코타일"] },
    { id: "aluminum", name: "알루미늄", riskLevel: "high", notes: "강알칼리 시 변색" },
    { id: "brass-bronze", name: "청동·황동", riskLevel: "high", notes: "일반적으로 산성 주의. 제트액티브 등 예외 제품 존재" },
    { id: "concrete", name: "콘크리트·시멘트", riskLevel: "medium", notes: "석회 성분. 산성 세정 가능하나 린스·건조 필수" },
    { id: "exterior-wall", name: "외벽·베란다 콘크리트 면", riskLevel: "medium", notes: "산성비로 석회가 유리로 흘러내리는 경우 많음" },
  ],
  contaminants: [
    { id: "limescale", name: "요석·석회·물때", type: "inorganic", phDirection: "alkaline", notes: "무기물. 산성 세정이 정석" },
    { id: "soap-scum", name: "비누찌꺼기", type: "mixed" },
    { id: "grease", name: "기름때·유기 오염", type: "organic", phDirection: "acidic" },
    { id: "mold", name: "곰팡이", type: "microbial", notes: "살균·표백과 근절은 별개. 실리콘 깊은 곰팡이는 제거 한계" },
    { id: "rust", name: "녹", type: "inorganic" },
    { id: "burnt-residue", name: "탄찌·그을음", type: "organic" },
    { id: "stain-discoloration", name: "찌든 때·변색", type: "mixed" },
    { id: "cement-residue", name: "백시멘트·시공 잔재", type: "inorganic", notes: "타일 시공 후 석회류. 강산 원액·집중 린스" },
    { id: "construction-dust", name: "공사 먼지·분진", type: "inorganic" },
    { id: "nicotine", name: "담배·니코틴 찌꺼기", type: "organic" },
  ],
  products: [
    {
      id: "kiehl-santex",
      brand: "Kiehl",
      name: "산텍스(Santex)",
      phType: "strong_acid",
      phApprox: "~1",
      mainUse: ["화장실", "요석", "석회", "비누찌꺼기"],
      standardDilution: "물 4L : 원액 20~40ml",
      strongDilution: "원액(변기 내측 굳은 요석)",
      dwellTime: "원액 5~10분",
      warnings: ["고무장갑·환기 필수", "락스 등 염소계와 혼합 금지", "대리석·에나멜 등 산성 약한 소재 사전 테스트"],
      confidence: "high",
      sources: [SRC.weekly],
    },
    {
      id: "kiehl-sanikal-eco",
      brand: "Kiehl",
      name: "사니칼-에코",
      phType: "acid",
      mainUse: ["화장실 일상 유지", "스테인레스 손잡이"],
      standardDilution: "1:200",
      warnings: ["분무 후 충분히 헹굼"],
      confidence: "high",
      sources: [SRC.mimi],
    },
    {
      id: "kiehl-oxycal",
      brand: "Kiehl",
      name: "옥시칼",
      phType: "oxidizing",
      mainUse: ["화장실 바닥·벽 타일", "약한 곰팡이 표백"],
      standardDilution: "1:200",
      dwellTime: "약 10분",
      warnings: ["현재 수입 중단(커뮤니티 언급)", "실리콘 깊은 곰팡이 한계", "산성제와 혼합 금지"],
      confidence: "medium",
      status: "discontinued",
      sources: [SRC.mimi, SRC.charlie4],
    },
    {
      id: "kiehl-veryprop",
      brand: "Kiehl",
      name: "베리프롭",
      phType: "weak_alkaline",
      phApprox: "pH 7.5~8.5 희석",
      mainUse: ["바닥 일상", "대리석·데코타일", "에폭시 바닥"],
      standardDilution: "1:200",
      strongDilution: "1:10",
      warnings: ["강세척 1:10 시 냄새", "대리석은 전용 바닥세정 원칙 우선"],
      confidence: "high",
      sources: [SRC.mimi, SRC.floor, SRC.charlie4],
    },
    {
      id: "kiehl-vinoxin-eco",
      brand: "Kiehl",
      name: "비녹신 에코",
      phType: "acid",
      mainUse: ["스테인레스", "계단 난간", "표면 녹"],
      standardDilution: "1:10",
      dwellTime: "도포 후 마른 걸레로 닦기",
      warnings: ["결 방향 작업", "린스는 물로 충분"],
      confidence: "high",
      sources: [SRC.mimi, SRC.rust],
    },
    {
      id: "kiehl-jet",
      brand: "Kiehl",
      name: "제트",
      phType: "acid",
      mainUse: ["수전", "스테인레스 강세척"],
      warnings: ["제트액티브와 별도 제품"],
      confidence: "high",
      sources: [SRC.mimi, SRC.jet],
    },
    {
      id: "kiehl-jet-active",
      brand: "Kiehl",
      name: "제트액티브",
      phType: "acid",
      mainUse: ["스테인레스 연마·묵은 얼룩", "싱크대 하얀 찌꺼기"],
      warnings: ["연마 성분 포함. 반복 작업·기계 연마 권장", "청동/황동은 별도 확인"],
      confidence: "high",
      sources: [SRC.jet],
    },
    {
      id: "kiehl-petronal-eco",
      brand: "Kiehl",
      name: "페트로날에코",
      phType: "acid",
      mainUse: ["샤워부스", "욕실 유리·타일"],
      warnings: ["심한 오염은 제트·엑손포르테 병행 검토"],
      confidence: "high",
      sources: [SRC.shower],
    },
    {
      id: "kiehl-glasking",
      brand: "Kiehl",
      name: "글라스킹",
      phType: "neutral",
      mainUse: ["유리 스퀴지 세정", "실내·외창 일상", "태양광 패널", "산성 세정 후 마무리"],
      standardDilution: "물 3~4L + 제품 적정량(희석)",
      strongDilution: "원액 시 유리 염분 제거 가능",
      warnings: ["산성 세정 후 물 헹굼 뒤 사용", "스퀴지 작업에 최적화", "버핑 시 거품 많음"],
      confidence: "high",
      sources: [SRC.glass3, SRC.glassWorkflow, SRC.mimi],
    },
    {
      id: "kiehl-graset",
      brand: "Kiehl",
      name: "그라셋",
      phType: "strong_alkaline",
      mainUse: ["주방 기름때", "후드·화구·스테인레스"],
      standardDilution: "약 1:100 권장",
      warnings: ["알루미늄·함석 변색 가능 — 사전 테스트", "고무장갑·환기", "가능하면 표면을 약 40~60℃ 온수로 적신다(끓는 물 금지)"],
      confidence: "high",
      sources: [SRC.kitchen, SRC.charlie4],
    },
    {
      id: "kiehl-exonforte",
      brand: "Kiehl",
      name: "엑손포르테",
      phType: "strong_alkaline",
      phApprox: "~13.5",
      mainUse: ["주방 기름·탄찌", "심한 유리·벽면 물때(2차)", "바닥·벽"],
      standardDilution: "원액 또는 약간 희석, 현장 테스트",
      dwellTime: "잠시 대기 후 세정",
      warnings: ["알루미늄 변색 주의", "친환경 인증이어도 호흡 보호 필요", "유리 1차 세정제로는 부적합"],
      confidence: "high",
      sources: [SRC.kitchen, SRC.glassLimescale],
    },
    {
      id: "kiehl-parketoclean",
      brand: "Kiehl",
      name: "파케토클린",
      phType: "neutral",
      mainUse: ["강마루·강화마루 일상 세정"],
      standardDilution: "1:320",
      warnings: ["섬유재(카펫) 제외", "별도 린스 불필요, 물기 제거"],
      confidence: "high",
      sources: [SRC.parketto],
    },
    {
      id: "kiehl-parketin",
      brand: "Kiehl",
      name: "파케틴",
      phType: "neutral",
      mainUse: ["강마루·강화마루", "밀폐·오일 처리 목재"],
      standardDilution: "1:320",
      warnings: ["원목·왁스 처리 목재 사용 금지"],
      confidence: "high",
      sources: [SRC.parketto],
    },
    {
      id: "kiehl-kallinex",
      brand: "Kiehl",
      name: "칼리넥스",
      phType: "strong_acid",
      phApprox: "~0.5",
      mainUse: ["주방 강산", "석회·백시멘트", "유리·벽면 석회때(2차)", "화장실 집중세정"],
      standardDilution: "원액 또는 진하게 희석, 표면에 약간의 물기 있을 때 반응 좋음",
      dwellTime: "도포 후 솔질·린스",
      warnings: ["대리석·합금 등 산성 약한 재질 주의", "하수구 유출 방지·충분 린스·완전 건조", "화장실 경제형 대안은 산텍스·페트로날에코"],
      confidence: "high",
      sources: [SRC.charlie4, SRC.glassLimescale, SRC.cementTile],
    },
    {
      id: "kiehl-powerfix-gel",
      brand: "Kiehl",
      name: "파워픽스젤",
      phType: "strong_acid",
      mainUse: ["스테인레스 녹"],
      warnings: ["물로 충분히 헹굼"],
      confidence: "medium",
      sources: [SRC.rust],
    },
    {
      id: "kiehl-ariston",
      brand: "Kiehl",
      name: "아리스톤",
      phType: "neutral",
      mainUse: ["바닥 광택·마무리"],
      standardDilution: "1:5",
      warnings: ["베리프롭 세정 후 얇게 걸레질"],
      confidence: "medium",
      sources: [SRC.floor],
    },
    {
      id: "kiehl-torban",
      brand: "Kiehl",
      name: "토르반",
      phType: "weak_alkaline",
      mainUse: ["입주청소 바닥", "일상·집중 겸용"],
      warnings: [],
      confidence: "medium",
      sources: [SRC.parketto],
    },
    {
      id: "kiehl-tornado",
      brand: "Kiehl",
      name: "토네이도",
      phType: "alkaline",
      mainUse: ["유리·외창 1차 세정", "외벽", "담배 찌꺼기", "방수 표면(목재 제외)"],
      standardDilution: "희석 사용",
      warnings: ["묵은 석회때 단독으로는 한계 — 2차 강산·강알칼리 검토", "거품 적음"],
      confidence: "high",
      sources: [SRC.glass3, SRC.glassLimescale],
    },
    {
      id: "kiehl-glassqueen",
      brand: "Kiehl",
      name: "글라스퀸",
      phType: "alkaline",
      mainUse: ["실내 유리 프리미엄", "지문·가벼운 물때", "글라스킹 전 잔수 제거"],
      standardDilution: "원액",
      warnings: ["걸레 작업 전용(스퀴지 비최적)", "빠른 건조 — 즉시 닦기"],
      confidence: "high",
      sources: [SRC.glass3, SRC.glassLimescale],
    },
    {
      id: "kiehl-binoxin-eco",
      brand: "Kiehl",
      name: "비녹스 에코",
      phType: "strong_acid",
      phApprox: "~0.5",
      mainUse: ["유리·벽면 석회때", "스테인레스", "칼리넥스 대체군"],
      standardDilution: "원액 또는 약간 희석",
      warnings: ["대리석·합금 주의", "표면에 약간 물기 있을 때 유리", "비녹신 에코와 별도 제품"],
      confidence: "high",
      sources: [SRC.glassLimescale],
    },
    {
      id: "kiehl-pinocet",
      brand: "Kiehl",
      name: "피노셋",
      phType: "unknown",
      mainUse: ["변기 탈취·위생 유지"],
      warnings: [
        "원액 제품 — 변기솔에 소량 또는 변기 뒤 안 보이는 곳에 소량",
        "분무기 대량 분사 비권장",
        "기존 악취·외부 냄새 역류 화장실에 역효과 가능",
      ],
      confidence: "medium",
      sources: [SRC.pinocet],
    },
    {
      id: "kiehl-kobet",
      brand: "Kiehl",
      name: "코베트",
      phType: "alkaline",
      mainUse: ["타일 집중세정"],
      warnings: ["현장 샘플 테스트"],
      confidence: "medium",
      sources: [SRC.glassLimescale, SRC.kitchen],
    },
  ],
  facts: [
    {
      id: "fact-santex-dilute",
      type: "dilution",
      productId: "kiehl-santex",
      materialIds: ["ceramic-tile", "porcelain"],
      contaminantId: "limescale",
      dilution: "물 4L : 20~40ml",
      body: "넓은 면적(타일·세면대 외관·변기 외부)은 버킷 희석액으로 스펀지·솔 세정.",
      confidence: "high",
      guidePaths: ["/services/office-regular/restroom", "/guides/water-faucet"],
      sources: [SRC.weekly],
    },
    {
      id: "fact-santex-undiluted",
      type: "procedure",
      productId: "kiehl-santex",
      materialIds: ["porcelain"],
      contaminantId: "limescale",
      dilution: "원액",
      dwellTime: "5~10분",
      tools: ["고무장갑", "변기솔", "청소 패드"],
      steps: ["원액 직접 도포", "5~10분 대기", "솔·패드로 문지르기", "물로 충분히 헹굼"],
      body: "변기 내측 굳은 요석·찌든 때는 희석 없이 원액 사용.",
      warnings: ["줄눈·수전 장시간 방치 금지"],
      confidence: "high",
      guidePaths: ["/services/office-regular/restroom", "/guides/water-faucet"],
      sources: [SRC.weekly],
    },
    {
      id: "fact-sanikal-daily",
      type: "usage",
      productId: "kiehl-sanikal-eco",
      materialIds: ["ceramic-tile", "stainless", "porcelain"],
      dilution: "1:200",
      tools: ["분무기"],
      body: "화장실 전반·스테인레스 손잡이 평소 유지보수용 분무 세정.",
      confidence: "high",
      guidePaths: ["/services/office-regular/restroom", "/services/stairs-regular/handrail"],
      sources: [SRC.mimi],
    },
    {
      id: "fact-oxycal-monthly",
      type: "procedure",
      productId: "kiehl-oxycal",
      materialIds: ["ceramic-tile"],
      contaminantId: "mold",
      dilution: "1:200",
      dwellTime: "약 10분",
      tools: ["밀대", "수세미"],
      steps: ["밀대 도포", "10분 대기", "수세미", "물 세정"],
      body: "화장실 바닥·변기·세면대·벽 타일 월 1회 또는 초기 집중 세정.",
      confidence: "medium",
      guidePaths: ["/guides/mold-tile"],
      sources: [SRC.mimi],
    },
    {
      id: "fact-veryprop-floor",
      type: "dilution",
      productId: "kiehl-veryprop",
      materialIds: ["marble", "pvc-deco", "epoxy-floor"],
      dilution: "1:200 (일상) / 1:10 (강세척)",
      body: "대리석·데코타일 바닥. 에폭시 코팅 바닥도 키엘 측 코팅 보호 성분 언급(코팅 상태 확인 필수).",
      confidence: "high",
      guidePaths: ["/services/commercial-regular/cafe", "/guides/marble-care"],
      sources: [SRC.mimi, SRC.floor],
    },
    {
      id: "fact-vinoxin-rail",
      type: "procedure",
      productId: "kiehl-vinoxin-eco",
      materialIds: ["stainless"],
      contaminantId: "rust",
      dilution: "1:10",
      tools: ["마른 걸레"],
      body: "계단 스테인레스 손잡이 도포 후 마른 걸레로 닦아냄.",
      confidence: "high",
      guidePaths: ["/services/stairs-regular/handrail"],
      sources: [SRC.mimi],
    },
    {
      id: "fact-graset-kitchen",
      type: "procedure",
      productId: "kiehl-graset",
      materialIds: ["ceramic-tile", "stainless"],
      contaminantId: "grease",
      tools: ["돌돌이", "16인치 연마솔", "방독면"],
      steps: ["현장 희석비율·반응시간 샘플 테스트", "기계+수작업 병행", "충분한 린스·환기"],
      body: "365일 미세척 주방의 콩기름·기름층 제거. 친환경 조건 현장은 샘플 작업이 필수.",
      confidence: "high",
      guidePaths: ["/services/commercial-regular/kitchen", "/guides/oil-stainless"],
      sources: [SRC.kitchen],
    },
    {
      id: "fact-jet-active-sink",
      type: "procedure",
      productId: "kiehl-jet-active",
      materialIds: ["stainless"],
      contaminantId: "stain-discoloration",
      tools: ["부드러운 스펀지", "매직스펀지", "흠집 없는 수세미", "그라인더(권장)"],
      steps: ["제품 도포", "결 방향으로 반복 연마", "물 헹굼"],
      body: "다른 키엘 산성·알칼리 제품으로 안 지워지는 싱크대 하얀 찌꺼기에 효과. 반복 작업 필요.",
      confidence: "high",
      guidePaths: ["/guides/oil-stainless", "/services/commercial-regular/kitchen"],
      sources: [SRC.jet],
    },
    {
      id: "fact-petronal-shower",
      type: "usage",
      productId: "kiehl-petronal-eco",
      materialIds: ["glass", "ceramic-tile"],
      contaminantId: "soap-scum",
      body: "샤워부스 청소에 산성이면서 알칼리성 장점을 담은 제품으로 커뮤니티 호평. 심한 오염은 제트·엑손포르테 검토.",
      confidence: "high",
      guidePaths: ["/guides/water-glass", "/services/move-in/bathroom"],
      sources: [SRC.shower],
    },
    {
      id: "fact-parketo-laminate",
      type: "dilution",
      productId: "kiehl-parketoclean",
      materialIds: ["laminate-wood"],
      dilution: "1:320",
      body: "강마루·강화마루 일상 세정. 린스 불필요, 마른 걸레로 물기 제거.",
      confidence: "high",
      guidePaths: ["/services/office-regular/floor", "/services/move-in/floor"],
      sources: [SRC.parketto],
    },
    {
      id: "fact-silicone-mold-limit",
      type: "material_rule",
      materialIds: ["silicone"],
      contaminantId: "mold",
      body: "실리콘 줄·창틀 곰팡이는 표면 세정으로는 한계. 깊이 침투 시 실리콘 재시공이 경제적.",
      confidence: "high",
      guidePaths: ["/guides/mold-tile", "/guides/mold-silicone", "/services/office-regular/restroom"],
      sources: [SRC.charlie4, SRC.mimi],
    },
    {
      id: "fact-marble-no-acid",
      type: "material_rule",
      materialIds: ["marble"],
      body: "대리석·라임스톤은 산성·강알칼리 모두 피함. 바닥 전용 중성·약알칼리 제품 사용.",
      confidence: "high",
      guidePaths: ["/guides/water-faucet", "/guides/marble-care"],
      sources: [SRC.charlie1, SRC.charlie4],
    },
    {
      id: "fact-rinse-water-only",
      type: "principle",
      body: "산성 세정 후 알칼리로 '중화'할 필요 없음. 물로 충분히 헹구고 잔수를 제거하면 됨.",
      confidence: "high",
      guidePaths: ["/guides/water-faucet", "/guides/marble-care"],
      sources: [SRC.charlie2],
    },
    {
      id: "fact-ph-not-power",
      type: "principle",
      body: "pH는 성질 지표이지 세정력 지수가 아님. 동일 pH라도 성분·용도가 다름.",
      confidence: "high",
      sources: [SRC.charlie2],
    },
    {
      id: "fact-no-mix-acid-bleach",
      type: "caution",
      body: "산성 세정제와 락스(염소계) 혼합 시 유독가스 위험. 산·알칼리 혼합도 금지.",
      warnings: ["절대 혼합 금지"],
      confidence: "high",
      sources: [SRC.weekly, SRC.charlie4],
    },
    {
      id: "fact-pretest",
      type: "principle",
      body: "재질·오염 확신 없으면 눈에 띄지 않는 구석에서 옅은 농도→진한 농도 순으로 사전 테스트.",
      confidence: "high",
      sources: [SRC.charlie1, SRC.charlie4],
    },
    {
      id: "fact-epoxy-wax-warning",
      type: "caution",
      materialIds: ["epoxy-floor"],
      body: "에폭시 바닥에 수지 왁스 코팅이 있으면 세제·물 사용 금지(왁스 용해). 코팅 없으면 베리프롭+밀대 걸레질, 돌돌이는 기스 위험.",
      confidence: "high",
      guidePaths: ["/services/commercial-regular/cafe"],
      sources: [SRC.floor],
    },
    {
      id: "fact-glass-two-stage",
      type: "principle",
      materialIds: ["glass"],
      contaminantId: "limescale",
      body: "유리세정제(토네이도·글라스킹 등)는 1차(먼지·가벼운 오염). 묵은 물때·석회는 2차로 엑손포르테(강알칼리) 또는 칼리넥스·비녹스에코(강산) — 오염원별로 부분 테스트 후 선택.",
      confidence: "high",
      guidePaths: [
        "/guides/water-glass",
        "/services/office-regular/glass",
        "/services/move-in/windows",
        "/services/commercial-regular/storefront",
      ],
      sources: [SRC.glassLimescale, SRC.glass3],
    },
    {
      id: "fact-glass-shower-vs-balcony",
      type: "principle",
      materialIds: ["glass"],
      body: "샤워부스 유리 오염=샴푸·비누·인체 기름. 베란다 외창=대기오염·석회·산성비. 같은 유리라도 오염원이 다르면 제품이 달라진다.",
      confidence: "high",
      guidePaths: ["/guides/water-glass", "/services/move-in/bathroom"],
      sources: [SRC.glass3],
    },
    {
      id: "fact-exterior-wall-sequence",
      type: "procedure",
      productId: "kiehl-tornado",
      materialIds: ["glass", "exterior-wall"],
      steps: ["1차 토네이도", "오염 테스트", "2차 엑손포르테 또는 비녹스에코/칼리넥스", "린스·잔수 제거"],
      body: "외벽·유리 키엘 권장 순서: 토네이도 1차 → 오염에 따라 2차 강알칼리 또는 강산.",
      confidence: "high",
      guidePaths: ["/services/move-in/windows", "/guides/water-glass"],
      sources: [SRC.glassLimescale],
    },
    {
      id: "fact-tile-daily-products",
      type: "usage",
      materialIds: ["ceramic-tile"],
      body: "타일 일상세정: 사니칼에코, 옥시칼, 페트로날에코, 산텍스(희석), 베리프롭 등. 집중세정: 제트(기계), 코베트, 엑손포르테, 비녹스에코 등.",
      confidence: "high",
      guidePaths: [
        "/services/office-regular/restroom",
        "/services/commercial-regular/restroom",
        "/services/move-in/bathroom",
        "/guides/mold-tile",
      ],
      sources: [SRC.glassLimescale],
    },
    {
      id: "fact-cement-kallinex",
      type: "procedure",
      productId: "kiehl-kallinex",
      materialIds: ["ceramic-tile", "concrete"],
      contaminantId: "cement-residue",
      dilution: "원액 또는 진한 희석",
      tools: ["비닐(하수구 막기)", "솔·수세미", "스퀴지", "마른 걸레"],
      steps: [
        "바닥에 물을 흥건히 뿌림",
        "하수구 입구 비닐로 막아 용액 유지",
        "칼리넥스 도포 후 솔질·밀어 올리기 반복",
        "비닐 제거 후 물로 충분히 린스",
        "스퀴지 또는 마른 걸레로 물기 완전 제거(건조 시 백화 재발 방지)",
      ],
      body: "타일 시공 후 백시멘트·석회 잔여물 제거. 건조 후 하얗게 올라오면 린스·건조 부족 신호.",
      warnings: ["고무장갑·환기", "대리석 접촉 금지"],
      confidence: "high",
      guidePaths: ["/services/move-in/bathroom", "/services/move-in/floor", "/guides/mold-tile"],
      sources: [SRC.cementTile],
    },
    {
      id: "fact-dry-wipe-principle",
      type: "principle",
      body: "세정 후 잔수에 세제·오염이 남으면 2차 오염·걸레자국 발생. 원칙적으로 마른 걸레 건조가 맞으나, 가벼운 오염·정기청소는 물기만 과하지 않으면 생략 가능. 입주·마감·고오염 바닥은 필수.",
      confidence: "high",
      guidePaths: [
        "/services/move-in/floor",
        "/services/office-regular/floor",
        "/services/commercial-regular/cafe",
        "/services/move-in/overview",
      ],
      sources: [SRC.dryWipe],
    },
    {
      id: "fact-place-not-category",
      type: "principle",
      body: "화장실세정제·유리세정제·바닥세정제 구분은 편의일 뿐. 오염원 → 재질 순으로 제품을 고르면 응용 범위가 넓어진다.",
      confidence: "high",
      sources: [SRC.glassLimescale, SRC.glass3, SRC.charlie1],
    },
    {
      id: "fact-pinocet-usage",
      type: "usage",
      productId: "kiehl-pinocet",
      materialIds: ["porcelain"],
      body: "변기솔에 소량, 또는 변기 뒤 안 보이는 곳에 소량. 냄새 덮기용이 아님. 역한 화장실·외부 냄새 유입 시 오히려 독될 수 있음.",
      confidence: "medium",
      guidePaths: ["/services/office-regular/restroom", "/guides/bathroom-odor"],
      sources: [SRC.pinocet],
    },
    {
      id: "fact-ticlean-santex-alt",
      type: "substitute",
      productId: "kiehl-santex",
      materialIds: ["ceramic-tile"],
      contaminantId: "limescale",
      body: "티크린 대체 문의 시 화장실 바닥+산성 집중세정이면 1순위 산텍스, 2순위 사니칼에코(욕실 전반). 재질·오염 확인 전 단정 불가.",
      confidence: "high",
      guidePaths: ["/services/office-regular/restroom", "/services/commercial-regular/restroom"],
      sources: [SRC.ticleanAlt],
    },
    {
      id: "fact-glass-squeegee-core",
      type: "principle",
      materialIds: ["glass"],
      tools: ["스퀴지", "극세사", "스크래퍼(공사 후)"],
      body: "유리 결과물은 세제보다 스퀴지·잔수 관리가 좌우. 공사 후 유리는 실리콘·페인트·콘크리트 스크래퍼 선행 후 세정.",
      confidence: "high",
      guidePaths: ["/guides/water-glass", "/services/move-in/windows", "/services/office-regular/glass"],
      sources: [SRC.glassWorkflow],
    },
  ],
  recipes: [
    {
      id: "recipe-toilet-limescale-santex",
      slug: "porcelain-toilet-limescale-santex",
      seoTitle: "변기 요석 제거 — 키엘 산텍스 | 클린아이덱스",
      field: "화장실",
      materialId: "porcelain",
      contaminantId: "limescale",
      productId: "kiehl-santex",
      factIds: ["fact-santex-undiluted", "fact-santex-dilute"],
      dilution: "내측 원액 / 외부 4L:20~40ml",
      dwellTime: "5~10분(원액)",
      tools: ["고무장갑", "변기솔", "버킷", "환기"],
      steps: [
        "고무장갑 착용·환기",
        "변기 내측 굳은 요석에 원액 도포 후 5~10분 대기",
        "솔·패드로 문지른 뒤 물 내림",
        "외부·타일은 희석액으로 닦고 물로 헹굼",
        "줄눈·수전에 잔여 산성이 남지 않게 린스",
      ],
      warnings: ["락스 혼합 금지", "대리석 접촉 주의"],
      summary: "변기 내측 요석은 산텍스 원액, 주변 타일은 희석액으로 처리하는 현장 표준 레시피.",
      confidence: "high",
      guidePaths: ["/services/office-regular/restroom", "/guides/water-faucet"],
      sources: [SRC.weekly],
    },
    {
      id: "recipe-restroom-daily-sanikal",
      slug: "restroom-daily-sanikal-eco",
      seoTitle: "화장실 일상 세정 — 사니칼에코 1:200 | 클린아이덱스",
      field: "화장실",
      materialId: "ceramic-tile",
      contaminantId: "soap-scum",
      productId: "kiehl-sanikal-eco",
      dilution: "1:200",
      dwellTime: "즉시 닦기",
      tools: ["분무기", "걸레"],
      steps: ["1:200 희석액 분무", "전면 닦기", "필요 시 물 걸레로 마무리"],
      warnings: [],
      summary: "화장실·스테인레스 손잡이 평소 유지보수용.",
      confidence: "high",
      guidePaths: ["/services/office-regular/restroom"],
      sources: [SRC.mimi],
    },
    {
      id: "recipe-stairs-rust-vinoxin",
      slug: "stainless-rail-rust-vinoxin-eco",
      seoTitle: "계단 스테인레스 녹·얼룩 — 비녹신에코 | 클린아이덱스",
      field: "계단",
      materialId: "stainless",
      contaminantId: "rust",
      productId: "kiehl-vinoxin-eco",
      dilution: "1:10",
      dwellTime: "도포 직후",
      tools: ["마른 걸레", "고무장갑"],
      steps: ["1:10 희석", "난간에 도포", "결 방향으로 마른 걸레에 닦기", "물로 잔여물 제거"],
      warnings: ["스크래치는 도구 선택에 따름 — 단면칼·스펀지 권장"],
      summary: "얕은 녹·얼룩에 비녹신에코 1:10.",
      confidence: "high",
      guidePaths: ["/services/stairs-regular/handrail"],
      sources: [SRC.mimi, SRC.rust],
    },
    {
      id: "recipe-kitchen-grease-graset",
      slug: "kitchen-floor-grease-graset",
      seoTitle: "주방 바닥 기름때 — 그라셋·엑손포르테 | 클린아이덱스",
      field: "주방",
      materialId: "ceramic-tile",
      contaminantId: "grease",
      productId: "kiehl-graset",
      dilution: "현장 테스트",
      dwellTime: "샘플 반응 시간 확인",
      tools: ["돌돌이", "연마솔", "방독면", "밀대"],
      steps: [
        "환기·보호구 착용",
        "올려진 구역에 희석액 샘플 테스트",
        "기계+수작업으로 기름층 제거",
        "충분한 물 린스·환기",
      ],
      warnings: ["알루미늄·함석 주의", "친환경 현장은 농도·시간 제한"],
      summary: "묵은 주방 기름때는 그라셋·엑손포르테 병행, 반드시 샘플 작업 후 전면 적용.",
      confidence: "high",
      guidePaths: ["/services/commercial-regular/kitchen", "/guides/oil-stainless"],
      sources: [SRC.kitchen],
    },
    {
      id: "recipe-shower-petronal",
      slug: "shower-booth-soap-scum-petronal-eco",
      seoTitle: "샤워부스 청소 — 페트로날에코 | 클린아이덱스",
      field: "욕실",
      materialId: "glass",
      contaminantId: "soap-scum",
      productId: "kiehl-petronal-eco",
      dilution: "라벨·QR 기준",
      dwellTime: "제품별",
      tools: ["스펀지", "스퀴지", "걸레"],
      steps: ["페트로날에코 도포", "문지르기", "물 헹굼", "유리는 글라스킹 마무리 선택"],
      warnings: ["심한 오염은 제트·엑손포르테 추가 검토"],
      summary: "샤워부스 비누찌꺼기·물때 일반 세정.",
      confidence: "high",
      guidePaths: ["/guides/water-glass", "/services/move-in/bathroom"],
      sources: [SRC.shower],
    },
    {
      id: "recipe-laminate-parketo",
      slug: "laminate-floor-daily-parketoclean",
      seoTitle: "강마루 일상 세정 — 파케토클린 1:320 | 클린아이덱스",
      field: "바닥",
      materialId: "laminate-wood",
      contaminantId: "grease",
      productId: "kiehl-parketoclean",
      dilution: "1:320",
      dwellTime: "즉시",
      tools: ["마른 걸레", "밀대"],
      steps: ["1:320 희석", "걸레질", "물기 완전 제거"],
      warnings: ["일반 바닥세정제 사용 금지"],
      summary: "강마루·강화마루 전용 일상 세정.",
      confidence: "high",
      guidePaths: ["/services/office-regular/floor"],
      sources: [SRC.parketto],
    },
    {
      id: "recipe-epoxy-veryprop",
      slug: "epoxy-floor-maintenance-veryprop",
      seoTitle: "에폭시 바닥 관리 — 베리프롭 | 클린아이덱스",
      field: "상가 바닥",
      materialId: "epoxy-floor",
      contaminantId: "grease",
      productId: "kiehl-veryprop",
      dilution: "1:200",
      dwellTime: "즉시",
      tools: ["밀대 걸레", "진공청소(코팅 시 제한)"],
      steps: ["왁스 코팅 여부 확인", "코팅 없으면 베리프롭 희석 걸레질", "아리스톤 1:5 얇은 마무리(선택)", "돌돌이는 기스 주의"],
      warnings: ["수지 왁스 코팅면은 세제·물 금지"],
      summary: "전시관·상가 에폭시 바닥 일상 관리.",
      confidence: "high",
      guidePaths: ["/services/commercial-regular/cafe"],
      sources: [SRC.floor],
    },
    {
      id: "recipe-sink-jet-active",
      slug: "stainless-sink-stain-jet-active",
      seoTitle: "싱크대 스테인레스 찌든 때 — 제트액티브 | 클린아이덱스",
      field: "주방",
      materialId: "stainless",
      contaminantId: "stain-discoloration",
      productId: "kiehl-jet-active",
      dilution: "원액 또는 라벨 기준",
      dwellTime: "반복 연마",
      tools: ["스펀지", "소형 그라인더(권장)"],
      steps: ["제트액티브 도포", "결 방향 연마(여러 회)", "물 헹굼"],
      warnings: ["가정용은 힘·시간 소요 큼"],
      summary: "다른 산·알칼리 제품으로 안 지워지는 싱크대 하얀 막에 최후 수단.",
      confidence: "high",
      guidePaths: ["/guides/oil-stainless"],
    },
    {
      id: "recipe-glass-limescale-acid",
      slug: "glass-limescale-binoxin-kallinex",
      seoTitle: "유리 석회·물때 2차 — 비녹스에코·칼리넥스 | 클린아이덱스",
      field: "유리",
      materialId: "glass",
      contaminantId: "limescale",
      productId: "kiehl-binoxin-eco",
      factIds: ["fact-glass-two-stage"],
      dilution: "원액 또는 약간 희석",
      dwellTime: "잠시 대기 후 세정",
      tools: ["고무장갑", "패드", "스퀴지", "극세사"],
      steps: [
        "1차 유리세정제(토네이도·글라스킹)로 먼지·가벼운 오염 제거",
        "안 지워지면 구역별 테스트",
        "표면에 약간 물기 있는 상태에서 비녹스에코 또는 칼리넥스 도포",
        "대기 후 문지르고 물로 충분히 헹굼",
        "스퀴지·극세사로 잔수 제거, 글라스킹·글라스퀸 마무리 선택",
      ],
      warnings: ["대리석·합금 주의", "유리세정제만으로는 묵은 석회 해결 불가"],
      summary: "베란다 외창 등 석회때 — 1차 유리세정 후 강산 2차.",
      confidence: "high",
      guidePaths: ["/guides/water-glass", "/services/move-in/windows", "/services/office-regular/glass"],
      sources: [SRC.glassLimescale],
    },
    {
      id: "recipe-glass-limescale-alkaline",
      slug: "glass-heavy-limescale-exonforte",
      seoTitle: "유리 심한 물때 2차 — 엑손포르테 | 클린아이덱스",
      field: "유리",
      materialId: "glass",
      contaminantId: "limescale",
      productId: "kiehl-exonforte",
      dilution: "원액 또는 약간 희석",
      dwellTime: "잠시 대기",
      tools: ["고무장갑", "패드", "스퀴지"],
      steps: ["1차 유리세정 실패 구역 테스트", "엑손포르테 도포·대기", "세정·린스", "잔수 제거"],
      warnings: ["알루미늄 프레임 주의", "산성 제품과 혼합 금지"],
      summary: "강산으로 안 될 때 강알칼리(엑손포르테) 테스트 — 오염원에 따라 선택.",
      confidence: "high",
      guidePaths: ["/guides/water-glass"],
      sources: [SRC.glassLimescale],
    },
    {
      id: "recipe-glass-daily-tornado-glasking",
      slug: "glass-daily-tornado-glasking",
      seoTitle: "유리 일상 세정 — 토네이도·글라스킹 | 클린아이덱스",
      field: "유리",
      materialId: "glass",
      contaminantId: "construction-dust",
      productId: "kiehl-tornado",
      dilution: "토네이도 희석 / 글라스킹 3~4L 물",
      dwellTime: "즉시",
      tools: ["분무기", "스퀴지", "극세사", "패드"],
      steps: ["오염 확인", "토네이도 희석 분사·패드", "스퀴지로 물 제거", "글라스킹 희석으로 마무리(선택)", "고객 검수"],
      warnings: ["묵은 석회는 2차 제품 필요"],
      summary: "상가·사무실 유리 일상 1차 세정 표준 흐름.",
      confidence: "high",
      guidePaths: [
        "/services/office-regular/glass",
        "/services/commercial-regular/storefront",
        "/services/move-in/windows",
      ],
      sources: [SRC.glass3, SRC.glassWorkflow],
    },
    {
      id: "recipe-tile-cement-kallinex",
      slug: "tile-cement-residue-kallinex",
      seoTitle: "타일 백시멘트 제거 — 칼리넥스 | 클린아이덱스",
      field: "입주·시공 후",
      materialId: "ceramic-tile",
      contaminantId: "cement-residue",
      productId: "kiehl-kallinex",
      factIds: ["fact-cement-kallinex"],
      dilution: "원액~진한 희석",
      dwellTime: "솔질 반복",
      tools: ["비닐", "솔", "수세미", "스퀴지", "마른 걸레"],
      steps: [
        "물 흥건히 → 하수구 비닐 막기",
        "칼리넥스 도포·솔질·밀어 올리기",
        "비닐 제거·물 린스",
        "스퀴지·마른 걸레로 완전 건조",
      ],
      warnings: ["백화 재발 시 린스·건조 부족", "환기·장갑"],
      summary: "리모델링 타일 백시멘트·석회 제거 정석.",
      confidence: "high",
      guidePaths: ["/services/move-in/bathroom", "/services/move-in/floor", "/services/move-in/overview"],
      sources: [SRC.cementTile],
    },
    {
      id: "recipe-restroom-floor-santex-ticlean",
      slug: "restroom-floor-limescale-santex",
      seoTitle: "화장실 바닥 요석 — 산텍스(티크린 대체) | 클린아이덱스",
      field: "화장실",
      materialId: "ceramic-tile",
      contaminantId: "limescale",
      productId: "kiehl-santex",
      dilution: "집중: 원액~진한 희석 / 일상: 4L:20~40ml",
      dwellTime: "5~10분(집중)",
      tools: ["고무장갑", "밀대", "솔"],
      steps: ["오염도 확인", "집중세정 또는 희석 선택", "도포·대기·솔질", "물 린스·잔수 제거"],
      warnings: ["줄눈·대리석 주의"],
      summary: "화장실 바닥 산성 집중세정 1순위 산텍스.",
      confidence: "high",
      guidePaths: [
        "/services/office-regular/restroom",
        "/services/commercial-regular/restroom",
        "/services/move-in/bathroom",
      ],
      sources: [SRC.ticleanAlt, SRC.weekly],
    },
  ],
  qaCases: [
    {
      id: "qa-silicone-mold",
      question: "화장실 실리콘 곰팡이는 어떤 제품이 좋을까요?",
      answerSummary:
        "약한 곰팡이는 옥시칼(표백·억제)이나 락스로 표면이 밝아질 수 있으나 근본 제거는 어렵습니다. 실리콘에 깊게 파고든 곰팡이는 어떤 곰팡이 세정제로도 한계가 있어 실리콘 교체가 현실적입니다. 키엘은 인체 위해를 고려해 전용 곰팡이 제거제를 만들지 않습니다.",
      relatedRecipeIds: [],
      relatedFactIds: ["fact-silicone-mold-limit"],
      confidence: "high",
      sources: [SRC.mimi, SRC.charlie4],
    },
    {
      id: "qa-mimi-routine",
      question: "사니칼·옥시칼·베리프롭·비녹신·제트 사용법이 맞나요?",
      answerSummary:
        "커뮤니티 매니저 검토상 큰 틀에서 틀리지 않았으며, 재질·오염에 맞으면 더 넓게 응용 가능합니다. 각 제품 QR·라벨을 우선 확인하고 현장 테스트를 권장합니다.",
      confidence: "high",
      sources: [SRC.mimi],
    },
    {
      id: "qa-acid-rinse",
      question: "산성 세제로 물때 제거 후 알칼리 중화가 필요한가요?",
      answerSummary: "아니요. 물로 충분히 헹구고 잔수를 제거하면 됩니다. 글라스킹 마무리는 중화가 아니라 오염 방지·광택 목적입니다.",
      relatedFactIds: ["fact-rinse-water-only"],
      confidence: "high",
      sources: [SRC.charlie2],
    },
    {
      id: "qa-glass-cleaner-limit",
      question: "유리세정제만 뿌리면 물때가 다 지워지나요?",
      answerSummary:
        "아니요. 유리세정제는 1차(먼지·가벼운 오염)용입니다. 묵은 석회·물때는 엑손포르테(강알칼리) 또는 칼리넥스·비녹스에코(강산) 등 2차 제품을 오염 구역별로 테스트해야 합니다.",
      relatedRecipeIds: ["recipe-glass-limescale-acid", "recipe-glass-limescale-alkaline"],
      relatedFactIds: ["fact-glass-two-stage"],
      confidence: "high",
      sources: [SRC.glassLimescale],
    },
    {
      id: "qa-dry-wipe",
      question: "세정 후 마른걸레질을 꼭 해야 하나요?",
      answerSummary:
        "원칙적으로 권장합니다. 잔수가 세제·오염을 다시 남기면 걸레자국·재오염이 생깁니다. 다만 가벼운 정기청소는 물기만 과하지 않으면 생략 가능하고, 입주·마감·고오염 바닥은 필수입니다. 재질에 따라 달라질 수 있습니다.",
      relatedFactIds: ["fact-dry-wipe-principle"],
      confidence: "high",
      sources: [SRC.dryWipe],
    },
    {
      id: "qa-cement-white-haze",
      question: "칼리넥스 작업 후 바닥이 다시 하얗게 올라오면?",
      answerSummary:
        "건조 후 보이는 백화는 석회 잔여물 신호입니다. 물 린스를 더 충분히 하고 스퀴지·마른 걸레로 물기를 완전히 제거해야 최종 상태가 됩니다. 필요 시 동일 절차 반복.",
      relatedRecipeIds: ["recipe-tile-cement-kallinex"],
      relatedFactIds: ["fact-cement-kallinex"],
      confidence: "high",
      sources: [SRC.cementTile],
    },
    {
      id: "qa-pinocet",
      question: "피노셋을 분무기에 넣어 써도 되나요?",
      answerSummary:
        "권장하지 않습니다. 원액 제품으로 변기솔에 소량, 또는 변기 뒤 안 보이는 곳에 소량 사용. 악취를 덮으려 쓰면 역효과 날 수 있습니다.",
      relatedFactIds: ["fact-pinocet-usage"],
      confidence: "medium",
      sources: [SRC.pinocet],
    },
    {
      id: "qa-ticlean-alt",
      question: "티크린 대신 키엘 무엇을 쓰나요?",
      answerSummary: "재질·오염 확인이 우선. 화장실 바닥 산성 집중세정이면 1순위 산텍스, 욕실 전반이면 사니칼에코도 적합합니다.",
      relatedRecipeIds: ["recipe-restroom-floor-santex-ticlean"],
      confidence: "high",
      sources: [SRC.ticleanAlt],
    },
  ],
  rules: [
    {
      id: "rule-material-first",
      title: "재질과 오염원을 먼저 본다",
      body: "장소(화장실·주방)보다 재질(타일·대리석·스테인레스)과 오염(요석·기름·곰팡이)을 먼저 매칭한다.",
      severity: "info",
      confidence: "high",
      sources: [SRC.charlie1],
    },
    {
      id: "rule-no-mix",
      title: "세정제 혼합 금지",
      body: "산성+염소(락스), 산성+알칼리 혼합은 유독가스·무력화·재질 손상을 유발한다.",
      severity: "critical",
      confidence: "high",
      sources: [SRC.charlie4, SRC.weekly],
    },
    {
      id: "rule-pretest",
      title: "사전 테스트 필수",
      body: "눈에 띄지 않는 구석에서 옅은 농도부터 반응 시간을 확인한 뒤 본 작업한다.",
      severity: "warning",
      confidence: "high",
      sources: [SRC.charlie1],
    },
    {
      id: "rule-water-rinse",
      title: "린스는 물로 충분",
      body: "산성 세정 후 알칼리 중화 작업은 불필요. 물 헹굼·잔수 제거가 정석이다.",
      severity: "info",
      confidence: "high",
      sources: [SRC.charlie2],
    },
    {
      id: "rule-cold-water-acid",
      title: "산성 희석은 찬물",
      body: "산성·대부분 바닥/유리 세정은 상온·찬물 희석이 기본. 그라셋은 가능하면 표면을 약 40~60℃ 온수로 적신다(끓는 물 금지). 엑손포르테는 묵은 기름때 온수 희석을 권장한다.",
      severity: "warning",
      confidence: "high",
      sources: [SRC.charlie4],
    },
    {
      id: "rule-glass-two-stage",
      title: "유리는 1차·2차 세정",
      body: "유리세정제로 먼지·가벼운 오염을 제거한 뒤, 묵은 물때·석회는 강산 또는 강알칼리 2차 제품을 구역별 테스트한다.",
      severity: "info",
      confidence: "high",
      sources: [SRC.glassLimescale],
    },
    {
      id: "rule-dry-wipe",
      title: "잔수 제거·마른 걸레",
      body: "입주·마감·고오염 바닥은 세정 후 스퀴지·마른 걸레로 물기를 제거한다. 가벼운 정기청소는 상황 판단.",
      severity: "warning",
      confidence: "high",
      sources: [SRC.dryWipe],
    },
    {
      id: "rule-contaminant-before-place",
      title: "장소보다 오염·재질",
      body: "화장실세정제·유리세정제 라벨은 편의 구분일 뿐. 오염원과 재질을 먼저 맞춘다.",
      severity: "info",
      confidence: "high",
      sources: [SRC.glassLimescale, SRC.glass3],
    },
    {
      id: "rule-cement-dry-finish",
      title: "석회 제거 후 완전 건조",
      body: "백시멘트·석회 제거 후 물기가 남으면 건조 시 하얀 백화가 재발한다. 린스 후 스퀴지·마른 걸레가 정석.",
      severity: "warning",
      confidence: "high",
      sources: [SRC.cementTile],
    },
  ],
};
