// Auto-generated from lib/demand/region-registry — scripts/generate-demand-regions.mjs
// 입주레이더(클린아이덱스)와 동일 시·군·구 목록

class MagamRegionDistrict {
  const MagamRegionDistrict(this.gu, this.slug);
  final String gu;
  final String slug;
}

class MagamRegionCity {
  const MagamRegionCity(this.id, this.label, this.districts);
  final String id;
  final String label;
  final List<MagamRegionDistrict> districts;

  /// 예: 서울 강남구, 경북 안동시
  String labelFor(MagamRegionDistrict district) => '$label ${district.gu}';
}

const kMagamRegionCities = <MagamRegionCity>[
  MagamRegionCity(
    "gangwon",
    "강원",
    [
      MagamRegionDistrict("강릉시", "gareusi-si"),
      MagamRegionDistrict("고성군", "goseogun-gun"),
      MagamRegionDistrict("동해시", "dohaesi-si"),
      MagamRegionDistrict("삼척시", "samcheogsi-si"),
      MagamRegionDistrict("속초시", "sogchosi-si"),
      MagamRegionDistrict("양구군", "yagugun-gun"),
      MagamRegionDistrict("양양군", "yayagun-gun"),
      MagamRegionDistrict("영월군", "yeoworgun-gun"),
      MagamRegionDistrict("원주시", "wonjusi-si"),
      MagamRegionDistrict("인제군", "injegun-gun"),
      MagamRegionDistrict("정선군", "jeoseongun-gun"),
      MagamRegionDistrict("철원군", "cheorwongun-gun"),
      MagamRegionDistrict("춘천시", "chuncheonsi-si"),
      MagamRegionDistrict("태백시", "taebaegsi-si"),
      MagamRegionDistrict("평창군", "pyeochagun-gun"),
      MagamRegionDistrict("홍천군", "hocheongun-gun"),
      MagamRegionDistrict("화천군", "hwacheongun-gun"),
      MagamRegionDistrict("횡성군", "hoeseogun-gun"),
    ],
  ),
  MagamRegionCity(
    "gyeonggi",
    "경기",
    [
      MagamRegionDistrict("가평군", "gapyeogun-gun"),
      MagamRegionDistrict("강화군", "gahwagun-gun"),
      MagamRegionDistrict("고양시 덕양구", "goya-deogyagu-gu"),
      MagamRegionDistrict("고양시 일산동구", "goya-irsandogu-gu"),
      MagamRegionDistrict("고양시 일산서구", "goya-irsanseogu-gu"),
      MagamRegionDistrict("과천시", "gwacheonsi-si"),
      MagamRegionDistrict("광명시", "gwamyeosi-si"),
      MagamRegionDistrict("광주시", "gwajusi-si"),
      MagamRegionDistrict("구리시", "gurisi-si"),
      MagamRegionDistrict("군포시", "gunposi-si"),
      MagamRegionDistrict("김포시", "gimposi-si"),
      MagamRegionDistrict("남양주시", "namyajusi-si"),
      MagamRegionDistrict("동두천시", "doducheonsi-si"),
      MagamRegionDistrict("미금시", "migeumsi-si"),
      MagamRegionDistrict("성남시 분당구", "seonam-bundagu-gu"),
      MagamRegionDistrict("성남시 수정구", "seonam-sujeogu-gu"),
      MagamRegionDistrict("성남시 중원구", "seonam-juwongu-gu"),
      MagamRegionDistrict("송탄시", "sotansi-si"),
      MagamRegionDistrict("수원시 권선구", "suwon-gwonseongu-gu"),
      MagamRegionDistrict("수원시 영통구", "suwon-yeotogu-gu"),
      MagamRegionDistrict("수원시 장안구", "suwon-jaangu-gu"),
      MagamRegionDistrict("수원시 팔달구", "suwon-pardargu-gu"),
      MagamRegionDistrict("시흥시", "siheusi-si"),
      MagamRegionDistrict("안산시 단원구", "ansan-danwongu-gu"),
      MagamRegionDistrict("안산시 상록구", "ansan-saroggu-gu"),
      MagamRegionDistrict("안성시", "anseosi-si"),
      MagamRegionDistrict("안양시 동안구", "anya-doangu-gu"),
      MagamRegionDistrict("안양시 만안구", "anya-manangu-gu"),
      MagamRegionDistrict("양주시", "yajusi-si"),
      MagamRegionDistrict("양평군", "yapyeogun-gun"),
      MagamRegionDistrict("여주시", "yeojusi-si"),
      MagamRegionDistrict("연천군", "yeoncheongun-gun"),
      MagamRegionDistrict("오산시", "osansi-si"),
      MagamRegionDistrict("옹진군", "ojingun-gun"),
      MagamRegionDistrict("용인시 기흥구", "yoin-giheugu-gu"),
      MagamRegionDistrict("용인시 수지구", "yoin-sujigu-gu"),
      MagamRegionDistrict("용인시 처인구", "yoin-cheoingu-gu"),
      MagamRegionDistrict("의왕시", "uiwasi-si"),
      MagamRegionDistrict("의정부시", "uijeobusi-si"),
      MagamRegionDistrict("이천시", "icheonsi-si"),
      MagamRegionDistrict("파주시", "pajusi-si"),
      MagamRegionDistrict("평택시", "pyeotaegsi-si"),
      MagamRegionDistrict("포천시", "pocheonsi-si"),
      MagamRegionDistrict("하남시", "hanamsi-si"),
      MagamRegionDistrict("화성시", "hwaseosi-si"),
    ],
  ),
  MagamRegionCity(
    "gyeongnam",
    "경남",
    [
      MagamRegionDistrict("거제시", "geojesi-si"),
      MagamRegionDistrict("거창군", "geochagun-gun"),
      MagamRegionDistrict("고성군", "goseogun-gun"),
      MagamRegionDistrict("김해시", "gimhaesi-si"),
      MagamRegionDistrict("남해군", "namhaegun-gun"),
      MagamRegionDistrict("밀양시", "miryasi-si"),
      MagamRegionDistrict("사천시", "sacheonsi-si"),
      MagamRegionDistrict("산청군", "sancheogun-gun"),
      MagamRegionDistrict("삼천포시", "samcheonposi-si"),
      MagamRegionDistrict("양산시", "yasansi-si"),
      MagamRegionDistrict("울주군", "urjugun-gun"),
      MagamRegionDistrict("의령군", "uiryeogun-gun"),
      MagamRegionDistrict("의창군", "uichagun-gun"),
      MagamRegionDistrict("장승포시", "jaseuposi-si"),
      MagamRegionDistrict("진주시", "jinjusi-si"),
      MagamRegionDistrict("창녕군", "chanyeogun-gun"),
      MagamRegionDistrict("창원시 마산합포구", "chawon-masanhabpogu-gu"),
      MagamRegionDistrict("창원시 마산회원구", "chawon-masanhoewongu-gu"),
      MagamRegionDistrict("창원시 성산구", "chawon-seosangu-gu"),
      MagamRegionDistrict("창원시 의창구", "chawon-uichagu-gu"),
      MagamRegionDistrict("창원시 진해구", "chawon-jinhaegu-gu"),
      MagamRegionDistrict("충무시", "chumusi-si"),
      MagamRegionDistrict("통영시", "toyeosi-si"),
      MagamRegionDistrict("하동군", "hadogun-gun"),
      MagamRegionDistrict("함안군", "hamangun-gun"),
      MagamRegionDistrict("함양군", "hamyagun-gun"),
      MagamRegionDistrict("합천군", "habcheongun-gun"),
    ],
  ),
  MagamRegionCity(
    "gyeongbuk",
    "경북",
    [
      MagamRegionDistrict("경산시", "gyeosansi-si"),
      MagamRegionDistrict("경주시", "gyeojusi-si"),
      MagamRegionDistrict("고령군", "goryeogun-gun"),
      MagamRegionDistrict("구미시", "gumisi-si"),
      MagamRegionDistrict("군위군", "gunwigun-gun"),
      MagamRegionDistrict("금릉군", "geumreugun-gun"),
      MagamRegionDistrict("김천시", "gimcheonsi-si"),
      MagamRegionDistrict("달성군", "darseogun-gun"),
      MagamRegionDistrict("문경시", "mungyeosi-si"),
      MagamRegionDistrict("봉화군", "bohwagun-gun"),
      MagamRegionDistrict("상주시", "sajusi-si"),
      MagamRegionDistrict("선산군", "seonsangun-gun"),
      MagamRegionDistrict("성주군", "seojugun-gun"),
      MagamRegionDistrict("안동시", "andosi-si"),
      MagamRegionDistrict("영덕군", "yeodeoggun-gun"),
      MagamRegionDistrict("영양군", "yeoyagun-gun"),
      MagamRegionDistrict("영일군", "yeoirgun-gun"),
      MagamRegionDistrict("영주시", "yeojusi-si"),
      MagamRegionDistrict("영천시", "yeocheonsi-si"),
      MagamRegionDistrict("영풍군", "yeopugun-gun"),
      MagamRegionDistrict("예천군", "yecheongun-gun"),
      MagamRegionDistrict("울릉군", "urreugun-gun"),
      MagamRegionDistrict("울진군", "urjingun-gun"),
      MagamRegionDistrict("의성군", "uiseogun-gun"),
      MagamRegionDistrict("점촌시", "jeomchonsi-si"),
      MagamRegionDistrict("청도군", "cheodogun-gun"),
      MagamRegionDistrict("청송군", "cheosogun-gun"),
      MagamRegionDistrict("칠곡군", "chirgoggun-gun"),
      MagamRegionDistrict("포항시 남구", "poha-namgu-gu"),
      MagamRegionDistrict("포항시 북구", "poha-buggu-gu"),
    ],
  ),
  MagamRegionCity(
    "gwangju",
    "광주",
    [
      MagamRegionDistrict("광산구", "gwasangu-gu"),
      MagamRegionDistrict("남구", "namgu-gu"),
      MagamRegionDistrict("동구", "dogu-gu"),
      MagamRegionDistrict("북구", "buggu-gu"),
      MagamRegionDistrict("서구", "seogu-gu"),
    ],
  ),
  MagamRegionCity(
    "daegu",
    "대구",
    [
      MagamRegionDistrict("남구", "namgu-gu"),
      MagamRegionDistrict("달서구", "darseogu-gu"),
      MagamRegionDistrict("달성군", "darseogun-gun"),
      MagamRegionDistrict("동구", "dogu-gu"),
      MagamRegionDistrict("북구", "buggu-gu"),
      MagamRegionDistrict("서구", "seogu-gu"),
      MagamRegionDistrict("수성구", "suseogu-gu"),
      MagamRegionDistrict("중구", "jung-gu"),
    ],
  ),
  MagamRegionCity(
    "daejeon",
    "대전",
    [
      MagamRegionDistrict("대덕구", "daedeoggu-gu"),
      MagamRegionDistrict("동구", "dogu-gu"),
      MagamRegionDistrict("서구", "seogu-gu"),
      MagamRegionDistrict("유성구", "yuseogu-gu"),
      MagamRegionDistrict("중구", "jung-gu"),
    ],
  ),
  MagamRegionCity(
    "busan",
    "부산",
    [
      MagamRegionDistrict("강서구", "gangseo-gu"),
      MagamRegionDistrict("금정구", "geumjeogu-gu"),
      MagamRegionDistrict("기장군", "gijagun-gun"),
      MagamRegionDistrict("남구", "namgu-gu"),
      MagamRegionDistrict("동구", "dogu-gu"),
      MagamRegionDistrict("동래구", "doraegu-gu"),
      MagamRegionDistrict("부산진구", "busanjingu-gu"),
      MagamRegionDistrict("북구", "buggu-gu"),
      MagamRegionDistrict("사상구", "sasagu-gu"),
      MagamRegionDistrict("사하구", "sahagu-gu"),
      MagamRegionDistrict("서구", "seogu-gu"),
      MagamRegionDistrict("수영구", "suyeogu-gu"),
      MagamRegionDistrict("연제구", "yeonjegu-gu"),
      MagamRegionDistrict("영도구", "yeodogu-gu"),
      MagamRegionDistrict("중구", "jung-gu"),
      MagamRegionDistrict("해운대구", "haeundaegu-gu"),
    ],
  ),
  MagamRegionCity(
    "seoul",
    "서울",
    [
      MagamRegionDistrict("강남구", "gangnam-gu"),
      MagamRegionDistrict("강동구", "gangdong-gu"),
      MagamRegionDistrict("강북구", "gangbuk-gu"),
      MagamRegionDistrict("강서구", "gangseo-gu"),
      MagamRegionDistrict("관악구", "gwanak-gu"),
      MagamRegionDistrict("광진구", "gwangjin-gu"),
      MagamRegionDistrict("구로구", "guro-gu"),
      MagamRegionDistrict("금천구", "geumcheon-gu"),
      MagamRegionDistrict("노원구", "nowon-gu"),
      MagamRegionDistrict("도봉구", "dobong-gu"),
      MagamRegionDistrict("동대문구", "dongdaemun-gu"),
      MagamRegionDistrict("동작구", "dongjak-gu"),
      MagamRegionDistrict("마포구", "mapo-gu"),
      MagamRegionDistrict("서대문구", "seodaemun-gu"),
      MagamRegionDistrict("서초구", "seocho-gu"),
      MagamRegionDistrict("성동구", "seongdong-gu"),
      MagamRegionDistrict("성북구", "seongbuk-gu"),
      MagamRegionDistrict("송파구", "songpa-gu"),
      MagamRegionDistrict("양천구", "yangcheon-gu"),
      MagamRegionDistrict("영등포구", "yeongdeungpo-gu"),
      MagamRegionDistrict("용산구", "yongsan-gu"),
      MagamRegionDistrict("은평구", "eunpyeong-gu"),
      MagamRegionDistrict("종로구", "jongno-gu"),
      MagamRegionDistrict("중구", "jung-gu"),
      MagamRegionDistrict("중랑구", "jungnang-gu"),
    ],
  ),
  MagamRegionCity(
    "sejong",
    "세종",
    [
      MagamRegionDistrict("세종시", "sejosi-si"),
    ],
  ),
  MagamRegionCity(
    "ulsan",
    "울산",
    [
      MagamRegionDistrict("남구", "namgu-gu"),
      MagamRegionDistrict("동구", "dogu-gu"),
      MagamRegionDistrict("북구", "buggu-gu"),
      MagamRegionDistrict("울주군", "urjugun-gun"),
      MagamRegionDistrict("중구", "jung-gu"),
    ],
  ),
  MagamRegionCity(
    "incheon",
    "인천",
    [
      MagamRegionDistrict("강화군", "gahwagun-gun"),
      MagamRegionDistrict("계양구", "gyeyagu-gu"),
      MagamRegionDistrict("남동구", "namdogu-gu"),
      MagamRegionDistrict("동구", "dogu-gu"),
      MagamRegionDistrict("미추홀구", "michuhorgu-gu"),
      MagamRegionDistrict("부평구", "bupyeogu-gu"),
      MagamRegionDistrict("서구", "seogu-gu"),
      MagamRegionDistrict("연수구", "yeonsugu-gu"),
      MagamRegionDistrict("옹진군", "ojingun-gun"),
      MagamRegionDistrict("중구", "jung-gu"),
    ],
  ),
  MagamRegionCity(
    "jeonnam",
    "전남",
    [
      MagamRegionDistrict("강진군", "gajingun-gun"),
      MagamRegionDistrict("고흥군", "goheugun-gun"),
      MagamRegionDistrict("곡성군", "gogseogun-gun"),
      MagamRegionDistrict("광양시", "gwayasi-si"),
      MagamRegionDistrict("구례군", "guryegun-gun"),
      MagamRegionDistrict("나주시", "najusi-si"),
      MagamRegionDistrict("담양군", "damyagun-gun"),
      MagamRegionDistrict("동광양시", "dogwayasi-si"),
      MagamRegionDistrict("목포시", "mogposi-si"),
      MagamRegionDistrict("무안군", "muangun-gun"),
      MagamRegionDistrict("보성군", "boseogun-gun"),
      MagamRegionDistrict("순천시", "suncheonsi-si"),
      MagamRegionDistrict("승주군", "seujugun-gun"),
      MagamRegionDistrict("신안군", "sinangun-gun"),
      MagamRegionDistrict("여수시", "yeosusi-si"),
      MagamRegionDistrict("영광군", "yeogwagun-gun"),
      MagamRegionDistrict("영암군", "yeoamgun-gun"),
      MagamRegionDistrict("완도군", "wandogun-gun"),
      MagamRegionDistrict("장성군", "jaseogun-gun"),
      MagamRegionDistrict("장흥군", "jaheugun-gun"),
      MagamRegionDistrict("진도군", "jindogun-gun"),
      MagamRegionDistrict("함평군", "hampyeogun-gun"),
      MagamRegionDistrict("해남군", "haenamgun-gun"),
      MagamRegionDistrict("화순군", "hwasungun-gun"),
    ],
  ),
  MagamRegionCity(
    "jeonbuk",
    "전북",
    [
      MagamRegionDistrict("고창군", "gochagun-gun"),
      MagamRegionDistrict("군산시", "gunsansi-si"),
      MagamRegionDistrict("금산군", "geumsangun-gun"),
      MagamRegionDistrict("김제시", "gimjesi-si"),
      MagamRegionDistrict("남원시", "namwonsi-si"),
      MagamRegionDistrict("무주군", "mujugun-gun"),
      MagamRegionDistrict("부안군", "buangun-gun"),
      MagamRegionDistrict("순창군", "sunchagun-gun"),
      MagamRegionDistrict("완주군", "wanjugun-gun"),
      MagamRegionDistrict("익산시", "igsansi-si"),
      MagamRegionDistrict("임실군", "imsirgun-gun"),
      MagamRegionDistrict("장수군", "jasugun-gun"),
      MagamRegionDistrict("전주시 덕진구", "jeonju-deogjingu-gu"),
      MagamRegionDistrict("전주시 완산구", "jeonju-wansangu-gu"),
      MagamRegionDistrict("정읍시", "jeoeubsi-si"),
      MagamRegionDistrict("진안군", "jinangun-gun"),
    ],
  ),
  MagamRegionCity(
    "jeju",
    "제주",
    [
      MagamRegionDistrict("서귀포시", "seogwiposi-si"),
      MagamRegionDistrict("제주시", "jejusi-si"),
    ],
  ),
  MagamRegionCity(
    "chungnam",
    "충남",
    [
      MagamRegionDistrict("계룡시", "gyeryosi-si"),
      MagamRegionDistrict("공주시", "gojusi-si"),
      MagamRegionDistrict("금산군", "geumsangun-gun"),
      MagamRegionDistrict("논산시", "nonsansi-si"),
      MagamRegionDistrict("당진시", "dajinsi-si"),
      MagamRegionDistrict("대덕군", "daedeoggun-gun"),
      MagamRegionDistrict("대천시", "daecheonsi-si"),
      MagamRegionDistrict("보령시", "boryeosi-si"),
      MagamRegionDistrict("부여군", "buyeogun-gun"),
      MagamRegionDistrict("서산시", "seosansi-si"),
      MagamRegionDistrict("서천군", "seocheongun-gun"),
      MagamRegionDistrict("아산시", "asansi-si"),
      MagamRegionDistrict("연기군", "yeongigun-gun"),
      MagamRegionDistrict("예산군", "yesangun-gun"),
      MagamRegionDistrict("온양시", "onyasi-si"),
      MagamRegionDistrict("천안시 동남구", "cheonan-donamgu-gu"),
      MagamRegionDistrict("천안시 서북구", "cheonan-seobuggu-gu"),
      MagamRegionDistrict("천원군", "cheonwongun-gun"),
      MagamRegionDistrict("청양군", "cheoyagun-gun"),
      MagamRegionDistrict("태안군", "taeangun-gun"),
      MagamRegionDistrict("홍성군", "hoseogun-gun"),
    ],
  ),
  MagamRegionCity(
    "chungbuk",
    "충북",
    [
      MagamRegionDistrict("괴산군", "goesangun-gun"),
      MagamRegionDistrict("단양군", "danyagun-gun"),
      MagamRegionDistrict("보은군", "boeungun-gun"),
      MagamRegionDistrict("옥천군", "ogcheongun-gun"),
      MagamRegionDistrict("음성군", "eumseogun-gun"),
      MagamRegionDistrict("제천시", "jecheonsi-si"),
      MagamRegionDistrict("증평군", "jeupyeogun-gun"),
      MagamRegionDistrict("진천군", "jincheongun-gun"),
      MagamRegionDistrict("청주시 상당구", "cheoju-sadagu-gu"),
      MagamRegionDistrict("청주시 서원구", "cheoju-seowongu-gu"),
      MagamRegionDistrict("청주시 청원구", "cheoju-cheowongu-gu"),
      MagamRegionDistrict("청주시 흥덕구", "cheoju-heudeoggu-gu"),
      MagamRegionDistrict("충주시", "chujusi-si"),
    ],
  ),
];

MagamRegionCity? magamCityById(String id) {
  for (final city in kMagamRegionCities) {
    if (city.id == id) return city;
  }
  return null;
}

MagamRegionCity get kMagamDefaultCity =>
    magamCityById('seoul') ?? kMagamRegionCities.first;

String magamRegionDisplayLabel(String cityId, String districtSlug) {
  final city = magamCityById(cityId);
  if (city == null) return districtSlug;
  for (final d in city.districts) {
    if (d.slug == districtSlug) return city.labelFor(d);
  }
  return districtSlug;
}
